### 1.Conceptos Basicos

In [1]:
#Código 1.1 holaMar: Saluda a Marta
def holaMar():
    print("Hola Marta!")
    print("Estoy programando en Python")

In [2]:
holaMar()

Hola Marta!
Estoy programando en Python


In [3]:
#Código 1.2 holaPab: Saluda a Pablo
def holaPab():
    print("Hola Pablo!")
    print("Estoy programando en Python")

In [4]:
holaPab()

Hola Pablo!
Estoy programando en Python


In [5]:
#Código 1.3 hola: Saluda a quien sea necesario
def hola(alguien):
    print("Hola", alguien,"!")
    print("Estoy programando en Python")

In [7]:
hola("Juan")

Hola Juan !
Estoy programando en Python


In [8]:
#Código 1.4 cuad1: Eleva un número al cuadrado y lo imprime
def cuad1(num):
    print (num*num)

In [10]:
cuad1(2)

4


In [11]:
#Código 1.5 cuad2: Pide un número al usuario e imprime su cuadrado
def cuad2():
    n = input("Ingrese un número: ")
    cuad1(int(n))

In [12]:
cuad2()

Ingrese un número: 2
4


In [13]:
#Código 1.6 cuadrado: Eleva un número al cuadrado y lo devuelve
def cuadrado(x):
    cua = x * x 
    return cua

In [16]:
y = cuadrado(5)
y

25

In [17]:
#Código 1.7 cuadrados: Imprime los cuadrados del 2 al 8
for x in range(2,9):
    print (cuadrado(x))

4
9
16
25
36
49
64


In [5]:
#Código 1.8 cuad.py: Imprime los cuadrados solicitados
def cuad():
    print("Se calcularan cuadrados de numeros")
    n1 = input("Ingrese un  numero entero: ")
    n2 = input("Ingrese otro  numero entero: ")

    n1 = int(n1)
    n2 = int(n2)
    for x in range(n1, n2):
        print (x*x)
    print("Es todo por ahora")

In [22]:
cuad()

Se calcularan cuadrados de numeros
Ingrese un  numero entero: 5
Ingrese otro  numero entero: 8
25
36
49
Es todo por ahora


### 2. Programas sencillos

### Código 2.1 ametrico.py: Convierte medidas inglesas a sistema metrico

In [3]:
def main():
    print("Convierte medidas inglesas a sistema métrico")
    millas = input("Cuántas Millas?: ")
    pies = input("Cuántos Pies?: ")
    pulgadas = input("Cuántas Pulgadas?: ")
    
    millas = int(millas)
    pies = int(pies)
    pulgadas = int(pulgadas)
    
    metros = 1609.344 * millas + 0.3048 * pies + 0.0254 * pulgadas
    print("La longitud es de", metros, "metros")

### Pruebas
#### 1 milla = 1609.344 m, 1 pie = 0.3048 m, 1 pulgada = 0.0254 m

In [5]:
main()

Convierte medidas inglesas a sistema métrico
Cuántas Millas?: 1
Cuántos Pies?: 0
Cuántas Pulgadas?: 0
La longitud es de 1609.344 metros


In [7]:
main()

Convierte medidas inglesas a sistema métrico
Cuántas Millas?: 0
Cuántos Pies?: 1
Cuántas Pulgadas?: 0
La longitud es de 0.3048 metros


In [8]:
main()

Convierte medidas inglesas a sistema métrico
Cuántas Millas?: 0
Cuántos Pies?: 0
Cuántas Pulgadas?: 1
La longitud es de 0.0254 metros


### 2.3.2 Expresiones

In [1]:
def ejercicio1():
    print("Ejercicio a")
    print("((b * b) - (4 * a * c)) / (2 * a)")
    a = input("Ingrese el valor de a: ")
    b = input("Ingrese el valor de b: ")
    c = input("Ingrese el valor de c: ")
    
    a = int(a)
    b = int(b)
    c = int(c)
    
    resultado = ((b * b) - (4 * a * c)) / (2 * a)
    
    print("El resultado de la expresion ((b * b) - (4 * a * c)) / (2 * a) es: ", resultado)

In [2]:
ejercicio1()

Ejercicio a
((b * b) - (4 * a * c)) / (2 * a)
Ingrese el valor de a: 10
Ingrese el valor de b: 100
Ingrese el valor de c: 1000
El resultado de la expresion ((b * b) - (4 * a * c)) / (2 * a) es:  -1500.0


In [13]:
((100 * 100) - (4 * 10 * 1000)) / (2 * 10)

-1500.0

In [3]:
def ejercicio2():
    print("Ejercicio b")
    print("(b * b - 4 * a * c) / (2 * a)")
    a = input("Ingrese el valor de a: ")
    b = input("Ingrese el valor de b: ")
    c = input("Ingrese el valor de c: ")
    
    a = int(a)
    b = int(b)
    c = int(c)
    
    resultado = (b * b - 4 * a * c) / (2 * a)
    
    print("El resultado de la expresion (b * b - 4 * a * c) / (2 * a) es: ", resultado)

In [4]:
ejercicio2()

Ejercicio b
(b * b - 4 * a * c) / (2 * a)
Ingrese el valor de a: 10
Ingrese el valor de b: 100
Ingrese el valor de c: 1000
El resultado de la expresion (b * b - 4 * a * c) / (2 * a) es:  -1500.0


In [5]:
def ejercicio3():
    print("Ejercicio c")
    print("b * b - 4 * a * c / 2 * a")
    a = input("Ingrese el valor de a: ")
    b = input("Ingrese el valor de b: ")
    c = input("Ingrese el valor de c: ")
    
    a = int(a)
    b = int(b)
    c = int(c)
    
    resultado = b * b - 4 * a * c / 2 * a
    
    print("El resultado de la expresion b * b - 4 * a * c / 2 * a es: ", resultado)

In [6]:
ejercicio3()

Ejercicio c
b * b - 4 * a * c / 2 * a
Ingrese el valor de a: 10
Ingrese el valor de b: 100
Ingrese el valor de c: 1000
El resultado de la expresion b * b - 4 * a * c / 2 * a es:  -190000.0


In [7]:
def ejercicio4():
    print("Ejercicio d")
    print("resultado = (b * b) - (4 * a * c / 2 * a)")
    a = input("Ingrese el valor de a: ")
    b = input("Ingrese el valor de b: ")
    c = input("Ingrese el valor de c: ")
    
    a = int(a)
    b = int(b)
    c = int(c)
    
    resultado = (b * b) - (4 * a * c / 2 * a)
    
    print("El resultado de la expresion (b * b) - (4 * a * c / 2 * a) es: ", resultado)

In [8]:
ejercicio4()

Ejercicio d
resultado = (b * b) - (4 * a * c / 2 * a)
Ingrese el valor de a: 10
Ingrese el valor de b: 100
Ingrese el valor de c: 1000
El resultado de la expresion (b * b) - (4 * a * c / 2 * a) es:  -190000.0


In [9]:
def ejercicio5():
    print("Ejercicio f")
    print("1 / 2 * b")
    b = input("Ingrese el valor de b: ")
    
    b = int(b)
    
    resultado = 1 / 2 * b
    
    print("El resultado de la expresion 1 / 2 * b es: ", resultado)

In [12]:
ejercicio5()

Ejercicio f
1 / 2 * b
Ingrese el valor de b: 100
El resultado de la expresion 1 / 2 * b es:  50.0


In [13]:
def ejercicio6():
    print("Ejercicio e")
    print("b/2")
    b = input("Ingrese el valor de b: ")
    
    b = int(b)
    
    resultado = b/2
    
    print("El resultado de la expresion b/2 es: ", resultado)

In [14]:
ejercicio6()

Ejercicio e
b/2
Ingrese el valor de b: 10
El resultado de la expresion b/2 es:  5.0


### 2.7 Una guía para el diseño 
### 2.8 Ejercicios 


In [26]:
#Ejercicio 2.4. Escribir un ciclo definido para imprimir por pantalla todos los números entre 10 y 20.
def imprimir10al20():
    for x in range(10,21):
        print(x)

In [27]:
imprimir10al20()

10
11
12
13
14
15
16
17
18
19
20


In [101]:
#Ejercicio 2.5. Escribir un ciclo definido que salude por pantalla a sus cinco mejores amigos/as.
def saludar5amigos():
    print("salude por pantalla a sus cinco mejores amigos/as")
    amigos = ["Juan", "Jose", "Miguel", "Carlos", "Raul"]
    for n in range(0,5):
        print("Hola",amigos[n])

In [102]:
saludar5amigos()

salude por pantalla a sus cinco mejores amigos/as
Hola Juan
Hola Jose
Hola Miguel
Hola Carlos
Hola Raul


In [99]:
#Ejercicio 2.6. Escribir un programa que use un ciclo definido con rango numérico, que pregunte los nombres de sus cinco mejores amigos/as, y los salude.
def preguntarsaludar5amigos():
    print("Este ejercicio consiste en preguntar los nombres de sus cinco mejores amigos/as, y los salude.")
    for x in range(1,6):
        nombre = input("ingrese nombre: ")
        print("Hola" ,nombre)

In [100]:
preguntarsaludar5amigos()

Este ejercicio consiste en preguntar los nombres de sus cinco mejores amigos/as, y los salude.
ingrese nombre: Juan
Hola Juan
ingrese nombre: Pedro
Hola Pedro
ingrese nombre: Jose
Hola Jose
ingrese nombre: Abraham
Hola Abraham
ingrese nombre: Raul
Hola Raul


In [106]:
#Ejercicio 2.7. Escribir un programa que use un ciclo definido con rango numérico, que pregunte los nombres de sus seis mejores amigos/as, y los salude.
def preguntarsaludar6amigos():
    print("Este ejercicio consiste en preguntar los nombres de sus seis mejores amigos/as, y los salude.")   
    for x in range(1,7):
        nombre = input("ingrese nombre: ")
        print("Hola" ,nombre)

In [107]:
preguntarsaludar6amigos()

Este ejercicio consiste en preguntar los nombres de sus seis mejores amigos/as, y los salude.
ingrese nombre: Juan
Hola Juan
ingrese nombre: Jose
Hola Jose
ingrese nombre: Beny
Hola Beny
ingrese nombre: Carlos
Hola Carlos
ingrese nombre: Raul
Hola Raul
ingrese nombre: Roberto
Hola Roberto


In [6]:
def consultarSaludar():
    """Ejercicio 2.8. Escribir un programa que use un ciclo definido con rango numérico, que averigue a cuántos amigos quieren saludar, les pregunte los nombres de esos amigos/as, y los salude."""
    print("Este ejercicio consiste en averiguar a cuántos amigos quieren saludar, les pregunte los nombres de esos amigos/as, y los salude.")
    amigos = input("A cuántos amigos desea saludar: ")
    amigos = int(amigos)
    for x in range(1, amigos+1):
        nombre = input("Ingrese nombre: ")
        print("Hola" ,nombre)
     


In [133]:
consultarSaludar()

Este ejercicio consiste en averiguar a cuántos amigos quieren saludar, les pregunte los nombres de esos amigos/as, y los salude.
A cuántos amigos desea saludar: 8
Ingrese nombre: a
Hola a
Ingrese nombre: b
Hola b
Ingrese nombre: c
Hola c
Ingrese nombre: d
Hola d
Ingrese nombre: e
Hola e
Ingrese nombre: f
Hola f
Ingrese nombre: g
Hola g
Ingrese nombre: h
Hola h


### 3. Funciones
### 3.1 Documentación de funciones

La documentación de una función se coloca luego del encabezado de la función, en un
párrafo encerrado entre """.
Cuando una función definida está correctamente documentada, es posible acceder a su documentación
mediante la función help provista por Python:

In [140]:
help(consultarSaludar)

Help on function consultarSaludar in module __main__:

consultarSaludar()
    Ejercicio 2.8. Escribir un programa que use un ciclo definido con rango numérico, que averigue a cuántos amigos quieren saludar, les pregunte los nombres de esos amigos/as, y los salude.



De esta forma no es necesario mirar el código de una función para saber lo que hace, simplemente
llamando a help es posible obtener esta información.

### 3.2 Imprimir versus devolver

Más útil que tener una biblioteca donde los resultados se imprimen por pantalla,
es contar con una biblioteca donde los resultados se devuelven, para que la gente que usa
esas funciones manipule esos resultados a voluntad: los imprima, los use para realizar cálculos
más complejos, etc.

In [159]:
def calc_asegundos (horas, minutos, segundos):
    """ Transforma en segundos una medida de tiempo expresada en
    horas, minutos y segundos """
    segsal = 3600 * horas + 60 * minutos + segundos # regla de transformación
    return segsal

De esta forma, es posible realizar distintas operaciones con el valor obtenido luego de hacer
la cuenta:

In [160]:
calc_asegundos(1,10,10)

4210

In [161]:
print ("Son", calc_asegundos(1, 10, 10), "segundos")

Son 4210 segundos


In [162]:
y = calc_asegundos(1, 10, 10)
z = calc_asegundos(2, 20, 20)
y+z

12630

### 3.2.1 Ejercicios

Ejercicio 3.1. Escribir una función repite_hola que reciba como parámetro un número entero n y escriba por pantalla el mensaje "Hola" n veces. Invocarla con distintos valores de n.

In [172]:
def repite_hola(n):
    repetir_hola = "hola"
    for x in range(1,n+1):
        print(repetir_hola)

In [173]:
repite_hola(4)

hola
hola
hola
hola


Ejercicio 3.2. Escribir otra función repite_hola que reciba como parámetro un número entero n y retorne la cadena formada por n concatenaciones de "Hola". Invocarla con distintos valores de n.

In [179]:
def repite_hola(n):
    repite_hola = "hola"
    for x in range(1,n+1):
        print(repite_hola)
    return x*repite_hola

In [180]:
repite_hola(3)

hola
hola
hola


'holaholahola'

### 3.3. Cómo usar una función en un programa

Una función es útil porque nos permite repetir la misma instrucción (puede que con argumentos distintos) todas las veces que las necesitemos en un programa.Para utilizar las funciones definidas anteriormente, escribiremos un programa que pida tres duraciones, y en los tres casos las transforme a segundos y las muestra por pantalla.

In [41]:
def print_asegundos(horas, minutos, segundos):
    """ Transforma en segundos una medida de tiempo expresada en
    horas, minutos y segundos """
    segsal = 3600 * horas + 60 * minutos + segundos
    print("Son",segsal, "segundos")
def main():
    """ Lee tres tiempos expresados en hs, min y seg, y usa print_asegundos para mostrar en pantalla la conversión a segundos """
    for x in range(3):
        hs = input("Cuantas horas?: ")
        min = input("Cuantos minutos?: ")
        seg = input("Cuantos segundos?: ")

        hs=int(hs)
        min=int(min)
        seg=int(seg)

        print_asegundos(hs, min, seg)

In [42]:
main()

Cuantas horas?: 1
Cuantos minutos?: 0
Cuantos segundos?: 0
Son 3600 segundos
Cuantas horas?: 0
Cuantos minutos?: 1
Cuantos segundos?: 0
Son 60 segundos
Cuantas horas?: 0
Cuantos minutos?: 0
Cuantos segundos?: 1
Son 1 segundos


In [21]:
help(main)

Help on function main in module __main__:

main()
    Lee tres tiempos expresados en hs, min y seg, y usa
     print_asegundos para mostrar en pantalla la conversión a
    segundos



### 3.5. Un ejemplo completo

Problema 3.1. Un usuario nos plantea su problema: necesita que se facture el uso de un teléfono. Nos informará la tarifa por segundo, cuántas comunicaciones se realizaron, la duración de cada comunicación expresada en horas, minutos y segundos. Como resultado deberemos informar la duración en segundos de cada comunicación y su costo.

In [51]:
def tarifador():
    """ El usuario ingresa la tarifa por segundo, cuántas
    comunicaciones se realizaron, y la duracion de cada
    comunicación expresada en horas, minutos y segundos. Como
    resultado se informa la duración en segundos de cada
    comunicación y su costo. """

    f= input("¿Cuánto cuesta 1 segundo de comunicacion?: ")
    n= input("¿Cuántas comunicaciones hubo?: ")
    
    f= float(f)
    n= int(n)
    
    for x in range(n):
        hs = input("¿Cuántas horas?: ")
        min = input("¿Cuántos minutos?: ")
        seg = input("¿Cuántos segundos?: ")
        
        hs = float(hs)
        min= float(min)
        seg= float(seg)
        
        segcalc = asegundos(hs, min, seg)
        costo = segcalc * f
        print("Duracion: ", segcalc, "segundos. Costo: ", costo, "$")
        
def asegundos(horas, minutos, segundos):
    segsal = 3600 * horas + 60 * minutos + segundos
    return segsal

In [55]:
tarifador()

¿Cuánto cuesta 1 segundo de comunicacion?: 0.40
¿Cuántas comunicaciones hubo?: 3
¿Cuántas horas?: 1
¿Cuántos minutos?: 0
¿Cuántos segundos?: 0
Duracion:  3600.0 segundos. Costo:  1440.0 $
¿Cuántas horas?: 0
¿Cuántos minutos?: 1
¿Cuántos segundos?: 0
Duracion:  60.0 segundos. Costo:  24.0 $
¿Cuántas horas?: 0
¿Cuántos minutos?: 0
¿Cuántos segundos?: 1
Duracion:  1.0 segundos. Costo:  0.4 $


### 3.6. Devolver Múltiples resultados

Ahora nos piden que escribamos una función que dada una duración en segundos sin fracciones (representada por un número entero) calcule la misma duración en horas, minutos y segundos.

In [3]:
def aHsMinSeg(x):
    """ Dada una duración en segundos sin fracciones
    (la función debe invocarse con números enteros)
    se la convierte a horas, minutos y segundos """
    hs = x / 3600
    min = (x % 3600) / 60
    seg = (x % 3600 ) % 60
    
    hs=int(hs)
    min=int(min)
    seg=int(seg)
    return (hs, min, seg)

In [4]:
(h, m, s) = aHsMinSeg(3661)
print("Son", h, "horas", m, "minutos", s, "segundos")

Son 1 horas 1 minutos 1 segundos


In [6]:
t = aHsMinSeg(3661)
print(t)

(1, 1, 1)


### 4. Decisiones

### 4.1 Expresiones booleanas

Además de los números y los textos que vimos hasta ahora, Python introduce las constantes True y False para representar los valores de verdad verdadero y falso respectivamente. Vimos que una expresión es un trozo de código Python que produce o calcula un valor (resultado). Una expresión booleana o expresión lógica es una expresión que vale o bien True o bien False.

### 4.1.1. Expresiones de comparación

a == b a es igual a b;
a != b a es distinto de b;
a < b a es menor que b;
a <= b a es menor o igual que b;
a > b a es mayor que b;
a >= b a es mayor o igual que b;

### 4.1.2 Operadores Lógicos

De la misma manera que se puede operar entre números mediante las operaciones de suma, esta, etc., también existen tres operadores lógicos para combinar expresiones booleanas: and (y), or (o) y not (no).

### 4.2. Comparaciones simples

Problema 4.1. Debemos leer un número y, si el número es positivo, debemos escribir en pantalla el cartel “Numero positivo”.

In [13]:
def es_positivo():
    x= input("ingrese un numero: ")
    x=int(x)
    if x > 0:
        print("Numero positivo")

In [14]:
es_positivo()

ingrese un numero: 4
Numero positivo


In [15]:
es_positivo()

ingrese un numero: -25


In [16]:
es_positivo()

ingrese un numero: 0


Problema 4.2. En la etapa de mantenimiento nos dicen que, en realidad, también se necesitaría un mensaje "Número no positivo" cuando no se cumple la condición.

In [30]:
def positivo_o_no():
    x= input("Ingrese un numero: ")
    x=int(x)
    if x > 0:
        print("Numero positivo: ")
    if not(x > 0):
        print("Numero no positivo")

In [28]:
positivo_o_no()

Ingrese un numero: 4
Numero positivo: 


In [31]:
positivo_o_no()

Ingrese un numero: -25
Numero no positivo


In [32]:
positivo_o_no()

Ingrese un numero: 0
Numero no positivo


### 4.3. Múltiples decisiones consecutivas

Problema 4.3. Si el número es positivo escribir un mensaje "Numero positivo", si el número es igual a 0 un mensaje "Igual a 0", y si el número es negativo escribir un mensaje "numero negativo".

In [45]:
def pcn1():
    x= input("Ingrese un numero: ")
    x=int(x)
    
    if x > 0:
        print("Numero positivo")
    else:
        if x==0:
            print("Igual a 0")
        else:
            print("Numero negativo")

In [38]:
pcn1()

Ingrese un numero: 4
Numero positivo


In [39]:
pcn1()

Ingrese un numero: -25
Numero negativo


In [40]:
pcn1()

Ingrese un numero: 0
Igual a 0


Esta estructura se conoce como de alternativas anidadas ya que dentro de una de las ramas de la alternativa (en este caso la rama del else) se anida otra alternativa. Pero ésta no es la única forma de implementarlo. Existe otra construcción, equivalente a la anterior pero que no exige sangrías cada vez mayores en el texto. Se trata de la estructura de alternativas encadenadas, que tiene la forma

In [41]:
def pcn2():
    x= input("Ingrese un numero: ")
    x=int(x)
    
    if x > 0:
        print("Numero positivo")
    elif x==0:
        print("Igual a 0")
    else:
        print("Numero negativo")

In [42]:
pcn2()

Ingrese un numero: 4
Numero positivo


In [43]:
pcn2()

Ingrese un numero: -25
Numero negativo


In [44]:
pcn2()

Ingrese un numero: 0
Igual a 0


### 4.4 Ejercicios

Ejercicio 4.1. El usuario del tarifador nos pide ahora una modificación, ya que no es lo mismo la tarifa por segundo de las llamadas cortas que la tarifa por segundo de las llamadas largas. Al inicio del programa se informará la duración máxima de una llamada corta, la tarifa de las llamadas cortas y la de las largas. Se deberá facturar con alguno de los dos valores de acuerdo a la duración de la comunicación.

Ejercicio 4.2. Mantenimiento del tarifador: 
a) Al nuevo programa que cuenta con llamadas cortas y largas, agregarle los adicionales, de modo que: Los montos se escriban como pesos y centavos. Se informe además cuál fue el total facturado en la corrida. 

In [95]:
def tarifador():
    print("-------------------------------------------------------------------------------------------------")
    tar= input("La tarifa de la llamada está fijada en pesos o centavos?, elija opción 1 o 2: ")
    tar= int(tar)
    if tar == 1:
        print("-------------------------------------------------------------------------------------------------")
        dur= input("Tarifa de la llamada fijada en pesos, es de corta o larga duración?, elija opción 1 o 2: ")
        dur=int(dur)
        if dur == 1:
            print("-------------------------------------------------------------------------------------------------")
            print("Tarifa de para llamadas de corta duración, fijada en pesos")
            
            print("-------------------------------------------------------------------------------------------------")
            f= input("¿Cuánto cuesta un segundo de comunicación?: ")
            f= float(f)
            
            print("-------------------------------------------------------------------------------------------------")
            n= input("¿Cuántas comunicaciones hubo: ")
            n=int(n)
            
            for x in range(n):
                print("-------------------------------------------------------------------------------------------------")
                hs = input("¿Cuántas horas?: ")
                min = input("¿Cuántos minutos?: ")
                seg = input("¿Cuántos segundos?: ")

                hs = float(hs)
                min= float(min)
                seg= float(seg)
                
                segcalc = asegundos(hs, min, seg)
                costo = segcalc * f
                print("-------------------------------------------------------------------------------------------------")
                print("Duracion: ", segcalc, "segundos. Costo: ", costo, "$")
        if dur == 2:
            print("-------------------------------------------------------------------------------------------------")
            print("Tarifa de para llamadas de larga duración, fijada en pesos")
            
            print("-------------------------------------------------------------------------------------------------")
            f= input("¿Cuánto cuesta un segundo de comunicación?: ")
            f= float(f)
            
            print("-------------------------------------------------------------------------------------------------")
            n= input("¿Cuántas comunicaciones hubo: ")
            n=int(n)
            
            for x in range(n):
                print("-------------------------------------------------------------------------------------------------")
                hs = input("¿Cuántas horas?: ")
                min = input("¿Cuántos minutos?: ")
                seg = input("¿Cuántos segundos?: ")

                hs = float(hs)
                min= float(min)
                seg= float(seg)
                
                segcalc = asegundos(hs, min, seg)
                costo = segcalc * f
                print("-------------------------------------------------------------------------------------------------")
                print("Duracion: ", segcalc, "segundos. Costo: ", costo, "$")

    elif tar == 2:
        print("-------------------------------------------------------------------------------------------------")
        dur= input("Tarifa de la llamada fijada en centavos, es de corta o larga duración?, elija opción 1 o 2: ")
        dur=int(dur)
        if dur == 1:
            print("-------------------------------------------------------------------------------------------------")
            print("Tarifa de para llamadas de corta duración, fijada en centavos")

            print("-------------------------------------------------------------------------------------------------")
            f= input("¿Cuánto cuesta un segundo de comunicación?: ")
            f= float(f)
            
            print("-------------------------------------------------------------------------------------------------")
            n= input("¿Cuántas comunicaciones hubo: ")
            n=int(n)
            
            for x in range(n):
                print("-------------------------------------------------------------------------------------------------")
                hs = input("¿Cuántas horas?: ")
                min = input("¿Cuántos minutos?: ")
                seg = input("¿Cuántos segundos?: ")

                hs = float(hs)
                min= float(min)
                seg= float(seg)
                
                segcalc = asegundos(hs, min, seg)
                costo = segcalc * f
                print("-------------------------------------------------------------------------------------------------")
                print("Duracion: ", segcalc, "segundos. Costo: ", costo, "¢")
        elif dur == 2:
            print("-------------------------------------------------------------------------------------------------")
            print("Tarifa de para llamadas de larga duración, fijada en centavos")

            print("-------------------------------------------------------------------------------------------------")
            f= input("¿Cuánto cuesta un segundo de comunicación?: ")
            f= float(f)
            
            print("-------------------------------------------------------------------------------------------------")
            n= input("¿Cuántas comunicaciones hubo: ")
            n=int(n)
            
            for x in range(n):
                print("-------------------------------------------------------------------------------------------------")
                hs = input("¿Cuántas horas?: ")
                min = input("¿Cuántos minutos?: ")
                seg = input("¿Cuántos segundos?: ")

                hs = float(hs)
                min= float(min)
                seg= float(seg)
                
                segcalc = asegundos(hs, min, seg)
                costo = segcalc * f
                print("-------------------------------------------------------------------------------------------------")
                print("Duracion: ", segcalc, "segundos. Costo: ", costo, "¢")
                
def asegundos(horas, minutos, segundos):
    segsal = 3600 * horas + 60 * minutos + segundos
    return segsal
 
tarifador()

-------------------------------------------------------------------------------------------------
La tarifa de la llamada está fijada en pesos o centavos?, elija opción 1 o 2: 1
-------------------------------------------------------------------------------------------------
Tarifa de la llamada fijada en pesos, es de corta o larga duración?, elija opción 1 o 2: 1
-------------------------------------------------------------------------------------------------
Tarifa de para llamadas de corta duración, fijada en pesos
-------------------------------------------------------------------------------------------------
¿Cuánto cuesta un segundo de comunicación?: 32
-------------------------------------------------------------------------------------------------
¿Cuántas comunicaciones hubo: 1
-------------------------------------------------------------------------------------------------
¿Cuántas horas?: 1
¿Cuántos minutos?: 0
¿Cuántos segundos?: 0
-----------------------------------------

### 5. Más sobre ciclos

Problema 5.1. El usuario debe poder ingresar muchos números y cada vez que se ingresa uno
debemos informar si es positivo, cero o negativo.
Utilizando los ciclos definidos vistos en las primeras unidades, es posible preguntarle al
usuario cada vez, al inicio del programa, cuántos números va a ingresar para consultar. La
solución propuesta resulta:

In [101]:
def muchos_pcn():
    i= input("Cuántos números quiere procesar: ")
    i=int(i)
    for j in range(0,i):
        x= input("Ingrese un número: ")
        x= int(x)
        if x > 0:
            print("Número positivo")
        elif x == 0: 
            print("Igual a 0")
        else:
            print("Numero negativo")
muchos_pcn()

Cuántos números quiere procesar: 2
Ingrese un número: 1
Número positivo
Ingrese un número: 1
Número positivo


Sin embargo al usuario considera que este programa no es muy intuitivo, porque lo obliga a contar de antemano cuántos números va a querer procesar, sin equivocarse, en lugar de ingresar uno a uno los números hasta procesarlos a todos.

### 5.1. Ciclos indefinidos

Para poder resolver este problema sin averiguar primero la cantidad de números a procesar, debemos introducir una instrucción que nos permita construir ciclos que no requieran que se informe de antemano la cantidad de veces que se repetirá el cálculo del cuerpo. Se trata de ciclos indefinidos en los cuales se repite el cálculo del cuerpo mientras una cierta condición es verdadera.

In [ ]:
while <condición>:
<hacer algo>

### 5.2. Ciclo interactivo

¿Cuál es la condición y cuál es el cuerpo del ciclo en nuestro problema? Claramente, el cuerpo del ciclo es el ingreso de datos y la verificación de si es positivo, negativo o cero. En cuanto a la condición, es que haya más datos para seguir calculando. Definimos una variable hayMasDatos, que valdrá “Si” mientras haya datos. Se le debe preguntar al usuario, después de cada cálculo, si hay o no más datos. Cuando el usuario deje de responder “Si”, dejaremos de ejecutar el cuerpo del ciclo. Una primera aproximación al código necesario para resolver este problema podría ser:

In [115]:
def pcn_loop():
    hayMasDatos = "Si"
    while hayMasDatos == "Si":
        x= input("Ingrese un numero: ")
        x= int(x)
        if x > 0:
            print("Numero Positivo: ")
        elif x == 0:
            print("Igual a 0")
        else:
            print("Número negativo")

        hayMasDatos = input("Desea continuar? <Si-No>: ")
        
pcn_loop()

Ingrese un numero: 25
Numero Positivo: 
Desea continuar? <Si-No>: Si
Ingrese un numero: 0
Igual a 0
Desea continuar? <Si-No>: Si
Ingrese un numero: -5
Número negativo
Desea continuar? <Si-No>: No


### 5.3. Ciclo con centinela

Un problema que tiene nuestra primera solución es que resulta poco amigable preguntarle al usuario después de cada cálculo si desea continuar. Se puede usar el método del centinela: un valor distinguido que, si se lee, le indica al programa que el usuario desea salir del ciclo. En este caso, podemos suponer que si ingresa el caracter * es una indicación de que desea terminar.

In [223]:
def pcn_loop2():
    
    x= input("Ingrese un numero ('*' para terminar):  ")
    while x != "*":
        x=int(x)    
        if x > 0:
            print("Numero Positivo: ")
        elif x == 0:
            print("Igual a 0")
        else:
            print("Número negativo")
        x= input("Ingrese un numero ('*' para terminar):  ")
        
    
pcn_loop2()

Ingrese un numero ('*' para terminar):  25
Numero Positivo: 
Ingrese un numero ('*' para terminar):  0
Igual a 0
Ingrese un numero ('*' para terminar):  -5
Número negativo
Ingrese un numero ('*' para terminar):  *


### 5.4 Cómo romper un ciclo

El ciclo con centinela es muy claro pero tiene un problema: hay dos lugares (la primera línea del cuerpo y la última línea del ciclo) donde se ingresa el mismo dato. Si en la etapa de mantenimiento tuviéramos que realizar un cambio en el ingreso del dato (cambio de mensaje, por ejemplo) deberíamos estar atentos y hacer dos correcciones iguales. Sería preferible poder leer el dato x en un único punto del programa. A continuación, tratamos de diseñar una solución con esa restricción.
Es claro que en ese caso la lectura tiene que estar dentro del ciclo para poder leer más de un
número, pero entonces la condición del ciclo no puede depender del valor leído, ni tampoco de
valores calculados dentro del ciclo. Pero un ciclo que no puede depender de valores leídos o calculados dentro de él será de la forma:

In [ ]:
while True:
    <hacer algo>

Un ciclo cuya condición es True parece ser un ciclo infinito (o sea que nunca va a terminar). ¡Pero eso es gravísimo! ¡Nuestros programas tienen que terminar! Afortunadamente hay una instrucción de Python, break, que nos permite salir de adentro de un ciclo (tanto sea for como while) en medio de su ejecución. En esta construcción:

In [ ]:
while <condicion>:
    <hacer algo_1>
    if <condif>:
        break
    <hacer algo_2>

Codificamos en Python la solución al problema de los números usando ese esquema:

In [224]:
def pcn_loop3():
    
    while True:
        x= input("Ingrese un numero ('*' para finalizar):  ")
        if str(x) == '*':
            break
        elif int(x)>0:
            print("Número positivo: ")
        elif int(x) == 0:
            print("Igual a 0")
        else:
            print("Número negativo")
            
pcn_loop3()

Ingrese un numero ('*' para finalizar):  25
Número positivo: 
Ingrese un numero ('*' para finalizar):  0
Igual a 0
Ingrese un numero ('*' para finalizar):  -5
Número negativo
Ingrese un numero ('*' para finalizar):  *


### 5.5 Ejercicios

Ejercicio 5.1. Nuevamente, se desea facturar el uso de un telefono. Para ello se informa la tarifa por segundo y la duracion de cada comunicacion expresada en horas, minutos y segundos. Como resultado se informa la duracion en segundos de cada comunicacion y su costo. Resolver este problema usando


5.1.1. Ciclo definido.

In [233]:
def tarifador_definido():
    """ El usuario ingresa la tarifa por segundo, cuántas
    comunicaciones se realizaron, y la duracion de cada
    comunicación expresada en horas, minutos y segundos. Como
    resultado se informa la duración en segundos de cada
    comunicación y su costo. """

    f= input("¿Cuánto cuesta 1 segundo de comunicacion?: ")
    n= input("¿Cuántas comunicaciones hubo?: ")
    
    f= float(f)
    n= int(n)
    
    for x in range(n):
        hs = input("¿Cuántas horas?: ")
        min = input("¿Cuántos minutos?: ")
        seg = input("¿Cuántos segundos?: ")
        
        hs = float(hs)
        min= float(min)
        seg= float(seg)
        
        segcalc = asegundos(hs, min, seg)
        costo = segcalc * f
        print("Duracion: ", segcalc, "segundos. Costo: ", costo, "$")
        
def asegundos(horas, minutos, segundos):
    segsal = 3600 * horas + 60 * minutos + segundos
    return segsal

tarifador_definido()

¿Cuánto cuesta 1 segundo de comunicacion?: 20
¿Cuántas comunicaciones hubo?: 1
¿Cuántas horas?: 1
¿Cuántos minutos?: 0
¿Cuántos segundos?: 2
Duracion:  3602.0 segundos. Costo:  72040.0 $


5.1.2. Ciclo interactivo.

In [28]:
def tarifador_interactivo():
    
    hayMasDatos = "Si"
    while hayMasDatos == "Si":
        f= float(input("¿Cuánto cuesta 1 segundo de comunicación?: "))
        
        hs = float(input("¿Cuántas horas?: "))
        min = float(input("¿Cuántos minutos?: "))
        seg = float(input("¿Cuántos segundos?: "))
        
        segcalc = asegundos(hs, min, seg)
        costo = segcalc * f
        print("Duracion: ", segcalc, "segundos. Costo: ", costo, "$")       

        hayMasDatos = input("Desea continuar? <Si-No>: ")
        
def asegundos(horas, minutos, segundos):
    segsal = 3600 * horas + 60 * minutos + segundos
    return segsal

tarifador_interactivo()

¿Cuánto cuesta 1 segundo de comunicación?: 2
¿Cuántas horas?: 3
¿Cuántos minutos?: 2
¿Cuántos segundos?: 1
Duracion:  10921.0 segundos. Costo:  21842.0 $
Desea continuar? <Si-No>: No


5.1.3. Ciclo con centinela.

In [267]:
def tarifador_centinela():
    x=input("¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): ")
    while x != "*":
        x=int(x)
        
        print('-----------------------------------------------------------------')
        hs = float(input("¿Cuántas horas?: "))
        min = float(input("¿Cuántos minutos?: "))
        seg = float(input("¿Cuántos segundos?: "))
        
        segcalc = asegundos(hs, min, seg)
        costo = segcalc * x
        print("Duracion: ", segcalc, "segundos. Costo: ", costo, "$")
        
        print('-----------------------------------------------------------------')
        x=input("¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): ")

def asegundos(horas, minutos, segundos):
    segsal = 3600 * horas + 60 * minutos + segundos
    return segsal        
        
            
tarifador_centinela()

¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): 6
-----------------------------------------------------------------
¿Cuántas horas?: 2
¿Cuántos minutos?: 14
¿Cuántos segundos?: 29
Duracion:  8069.0 segundos. Costo:  48414.0 $
-----------------------------------------------------------------
¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): 3
-----------------------------------------------------------------
¿Cuántas horas?: 1
¿Cuántos minutos?: 38
¿Cuántos segundos?: 54
Duracion:  5934.0 segundos. Costo:  17802.0 $
-----------------------------------------------------------------
¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): *


5.1.4. Ciclo “infinito” que se rompe.

In [12]:
def tarifador_infinito():
    while True:
        print('-----------------------------------------------------------------')
        x=input("¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): ")
        
        if str(x) == '*':
            break
        else:
            hs = float(input("¿Cuántas horas?: "))
            min = float(input("¿Cuántos minutos?: "))
            seg = float(input("¿Cuántos segundos?: "))
            
            segcalc = asegundos(hs, min, seg)
            costo = segcalc * int(x)
            print("Duracion: ", segcalc, "segundos. Costo: ", costo, "$")
        
def asegundos(horas, minutos, segundos):
    segsal = 3600 * horas + 60 * minutos + segundos
    return segsal
            
tarifador_infinito()

-----------------------------------------------------------------
¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): 2
¿Cuántas horas?: 1
¿Cuántos minutos?: 0
¿Cuántos segundos?: 0
Duracion:  3600.0 segundos. Costo:  7200.0 $
-----------------------------------------------------------------
¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): 3
¿Cuántas horas?: 2
¿Cuántos minutos?: 30
¿Cuántos segundos?: 25
Duracion:  9025.0 segundos. Costo:  27075.0 $
-----------------------------------------------------------------
¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): *


Ejercicio 5.2. Mantenimiento del tarifador: al final del día se debe informar cuántas llamadas
hubo y el total facturado. Hacerlo con todos los esquemas anteriores.

5.2.1. Ciclo definido

In [2]:
def tarifador_definido():
    """ El usuario ingresa la tarifa por segundo, cuántas
    comunicaciones se realizaron, y la duracion de cada
    comunicación expresada en horas, minutos y segundos. Como
    resultado se informa la duración en segundos de cada
    comunicación y su costo. """

    total = 0
    
    f= input("¿Cuánto cuesta 1 segundo de comunicacion?: ")
    n= input("¿Cuántas comunicaciones hubo?: ")
    
    f= float(f)
    n= int(n)
    
    for x in range(n):
        hs = input("¿Cuántas horas?: ")
        min = input("¿Cuántos minutos?: ")
        seg = input("¿Cuántos segundos?: ")
        
        hs = float(hs)
        min= float(min)
        seg= float(seg)
        
        segcalc = asegundos(hs, min, seg)
        costo = segcalc * f
        print("Duracion: ", segcalc, "segundos. Costo: ", costo, "$")
        print("------------------------------------------------------------------------")
        total = total + costo
        
    print("Reporte diario")
    x = x+1
    print("Total de comunicaciones:", x)
    print("Total Facturado: $", total)
    
    
def asegundos(horas, minutos, segundos):
    segsal = 3600 * horas + 60 * minutos + segundos
    return segsal

tarifador_definido()

¿Cuánto cuesta 1 segundo de comunicacion?: 2
¿Cuántas comunicaciones hubo?: 2
¿Cuántas horas?: 1
¿Cuántos minutos?: 0
¿Cuántos segundos?: 0
Duracion:  3600.0 segundos. Costo:  7200.0 $
------------------------------------------------------------------------
¿Cuántas horas?: 2
¿Cuántos minutos?: 0
¿Cuántos segundos?: 0
Duracion:  7200.0 segundos. Costo:  14400.0 $
------------------------------------------------------------------------
Reporte diario
Total de comunicaciones: 2
Total Facturado: $ 21600.0


5.2.2. Ciclo interactivo

In [38]:
def tarifador_interactivo():
    total=0
    cant=0
    
    hayMasDatos = "Si"
    while hayMasDatos == "Si":
        f= float(input("¿Cuánto cuesta 1 segundo de comunicación?: "))
        
        hs = float(input("¿Cuántas horas?: "))
        min = float(input("¿Cuántos minutos?: "))
        seg = float(input("¿Cuántos segundos?: "))
        
        segcalc = asegundos(hs, min, seg)
        costo = segcalc * f
        print("Duracion: ", segcalc, "segundos. Costo: ", costo, "$")       
        print("--------------------------------------")

        hayMasDatos = input("Desea continuar? <Si-No>: ")
        print("--------------------------------------") 
        
        total = total + costo
        cant = cant + 1
    else:  
        print("Reporte Diario")
        print("Total de comunicaciones: ", cant)
        print("Total facturado: $", total)
        
def asegundos(horas, minutos, segundos):
    segsal = 3600 * horas + 60 * minutos + segundos
    return segsal

tarifador_interactivo()

¿Cuánto cuesta 1 segundo de comunicación?: 2
¿Cuántas horas?: 3
¿Cuántos minutos?: 2
¿Cuántos segundos?: 1
Duracion:  10921.0 segundos. Costo:  21842.0 $
--------------------------------------
Desea continuar? <Si-No>: Si
--------------------------------------
¿Cuánto cuesta 1 segundo de comunicación?: 2
¿Cuántas horas?: 3
¿Cuántos minutos?: 1
¿Cuántos segundos?: 2
Duracion:  10862.0 segundos. Costo:  21724.0 $
--------------------------------------
Desea continuar? <Si-No>: No
--------------------------------------
Reporte Diario
Total de comunicaciones:  2
Total facturado: $ 43566.0


5.2.3. Ciclo con centinela

In [35]:
def tarifador_centinela():
    
    total= 0
    cant= 0
    
    x=input("¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): ")
    while x != "*":
        x=int(x)
        
        print('-----------------------------------------------------------------')
        hs = float(input("¿Cuántas horas?: "))
        min = float(input("¿Cuántos minutos?: "))
        seg = float(input("¿Cuántos segundos?: "))
        
        segcalc = asegundos(hs, min, seg)
        costo = segcalc * x
        print("Duracion: ", segcalc, "segundos. Costo: ", costo, "$")
        
        print('-----------------------------------------------------------------')
        x=input("¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): ")
        
        cant = cant + 1
        total = total + costo
        
    else:
        print('-----------------------------------------------------------------')
        print("Reporte diario")
        print("Cantidad de llamadas: ", cant)
        print("Total facturado: $", total)

def asegundos(horas, minutos, segundos):
    segsal = 3600 * horas + 60 * minutos + segundos
    return segsal        
        
            
tarifador_centinela()

¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): 2
-----------------------------------------------------------------
¿Cuántas horas?: 3
¿Cuántos minutos?: 2
¿Cuántos segundos?: 1
Duracion:  10921.0 segundos. Costo:  21842.0 $
-----------------------------------------------------------------
¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): 2
-----------------------------------------------------------------
¿Cuántas horas?: 2
¿Cuántos minutos?: 3
¿Cuántos segundos?: 1
Duracion:  7381.0 segundos. Costo:  14762.0 $
-----------------------------------------------------------------
¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): *
-----------------------------------------------------------------
Reporte diario
Cantidad de llamadas:  2
Total facturado: $ 36604.0


5.2.4. Ciclo "infinito" que se rompe

In [42]:
def tarifador_infinito():
    total = 0
    cant = 0 
    while True:
        print('-----------------------------------------------------------------')
        x=input("¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): ")
        
        if str(x) == '*':
            print('-----------------------------------------------------------------')
            print("Reporte Diario")
            print("Total de comunicaciones: ", cant)
            print("Total facturado: $", total)
            
            break
        else:
            hs = float(input("¿Cuántas horas?: "))
            min = float(input("¿Cuántos minutos?: "))
            seg = float(input("¿Cuántos segundos?: "))
            
            segcalc = asegundos(hs, min, seg)
            costo = segcalc * int(x)
            print("Duracion: ", segcalc, "segundos. Costo: ", costo, "$")
            total = total + costo
            cant = cant + 1
        
def asegundos(horas, minutos, segundos):
    segsal = 3600 * horas + 60 * minutos + segundos
    return segsal
            
tarifador_infinito()

-----------------------------------------------------------------
¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): 2
¿Cuántas horas?: 3
¿Cuántos minutos?: 2
¿Cuántos segundos?: 1
Duracion:  10921.0 segundos. Costo:  21842.0 $
-----------------------------------------------------------------
¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): 2
¿Cuántas horas?: 3
¿Cuántos minutos?: 1
¿Cuántos segundos?: 2
Duracion:  10862.0 segundos. Costo:  21724.0 $
-----------------------------------------------------------------
¿Cuánto cuesta 1 segundo de comunicación? ('*' para terminar): *
-----------------------------------------------------------------
Reporte Diario
Total de comunicaciones:  2
Total facturado: $ 43566.0


Ejercicio 5.3. Nos piden que escribamos una función que le pida al usuario que ingrese un número positivo. Si el usuario ingresa cualquier cosa que no sea lo pedido se le debe informar de su error mediante un mensaje y volverle a pedir el número.

5.3.1. Ciclo interactivo

In [17]:
def positivo_interactivo():
    hayMasDatos = "Si"
    while hayMasDatos == "Si":
        x=int(input("Ingrese un número positivo: "))
        if x >0:
            print("Número positivo")
            hayMasDatos = input("Desea continuar? <Si-No>: ")
            print("--------------------------------------") 
        else:
            print("Error, no es un número positivo: ")
            
positivo_interactivo()

Ingrese un número positivo: 2
Número positivo
Desea continuar? <Si-No>: Si
--------------------------------------
Ingrese un número positivo: -2
Error, no es un número positivo: 
Ingrese un número positivo: 2
Número positivo
Desea continuar? <Si-No>: Si
--------------------------------------
Ingrese un número positivo: 2
Número positivo
Desea continuar? <Si-No>: No
--------------------------------------


5.3.2. Ciclo con centinela

In [28]:
def positivo_centinela():
    
    x=input("Ingrese un número('*' para terminar): ")   
    while x != "*":
        x=int(x)
        if x > 0: 
            print("Numero positivo")
        else:
            print("Error, ingrese un número positivo")
        
        x=input("Ingrese un número('*' para terminar): ")   
positivo_centinela()

Ingrese un número('*' para terminar): 2
Numero positivo
Ingrese un número('*' para terminar): -3
Error, ingrese un número positivo
Ingrese un número('*' para terminar): 2
Numero positivo
Ingrese un número('*' para terminar): *


5.3.3. Ciclo "infinito" que se rompe

In [38]:
def positivo_infinito(): 
    while True: 
        x=input("Ingrese un número positivo('*' para terminar): ")
        if str(x) == "*":
            break
        elif int(x) > 0:
            print("Número positivo: ")
        elif int(x) < 0:
            print("Error, ingrese un número positivo")     
positivo_infinito()

Ingrese un número positivo('*' para terminar): -2
Error, ingrese un número positivo
Ingrese un número positivo('*' para terminar): 2
Número positivo: 
Ingrese un número positivo('*' para terminar): *


### 6. Cadenas de caracteres

### 6.1. Operaciones con cadenas

In [ ]:
# Ya vimos en la sección 2.4 que es posible:
# Sumar cadenas entre sí (y el resultado es la concatenación de todas las cadenas dadas):
>>> "Un divertido "+"programa "+"de "+ "radio"
’Un divertido programa de radio’
>>>
#Multiplicar una cadena s por un número k (y el resultado es la concatenación de s consigo
misma, k veces):
>>> 3*"programas "
’programas programas programas ’
>>> "programas "*3
’programas programas programas ’
>>>

### 6.1.1. Obtener el largo de una cadena

In [41]:
len("programas ")

10

Existe una cadena especial, que llamaremos cadena vacía, que es la cadena que no contiene ningún carácter (se la indica sólo con un apóstrofe o comilla que abre, y un apóstrofe o comilla que cierra), y que por lo tanto tiene longitud cero:

In [42]:
s=""
s

''

In [43]:
len(s)

0

### 6.1.2. Una operación para recorrer todos los caracteres de una cadena

In [44]:
for x in "programas ":
    print(x)

p
r
o
g
r
a
m
a
s
 


### 6.1.3. Acceder a una posición de la cadena

In [54]:
a="Veronica"
a[1]

'e'

### 6.2. Segmentos de cadenas

Python ofrece también una notación para identificar segmentos de una cadena. La notación es similar a la de los rangos que vimos en los ciclos definidos: a [0:2] se refiere a la subcadena formada por los caracteres cuyos índices están en el rango  [0,2):

In [46]:
a[0:2]

'Ve'

In [47]:
a[-4:-2]

'ni'

Si j es un entero no negativo, se puede usar la notación a[:j] para representar al
segmento a[0:j]; también se puede usar la notación a[j:] para representar al segmento
a[j:len(a)].

In [48]:
a[:3]

'Ver'

In [55]:
a[3:]

'onica'

Pero hay que tener cuidado con salirse del rango (en particular hay que tener cuidado con la cadena vacía):

In [56]:
a[10]

IndexError: string index out of range

In [57]:
s

''

In [58]:
len(s)

0

In [59]:
s[0]

IndexError: string index out of range

Sin embargo s[0:0] no da error.

In [60]:
s[0:0]

''

### 6.3. Las cadenas son inmutables

Nos dicen que la persona sobre la que estamos hablando en realidad se llama "Veronika"(sí, con "k"). Como conocemos la notación de corchetes, tratamos de corregir sólo el carácter correspondiente de la variable a:

In [61]:
a[6]="k"

TypeError: 'str' object does not support item assignment

El error que se despliega nos dice que la cadena no soporta la modificación de un carácter. Decimos que las cadenas son inmutables. Si queremos corregir la ortografía de una cadena, debemos hacer que la cadena a se refiera a otro valor:

In [62]:
a="Veronika"
a

'Veronika'

### 6.4. Procesamiento sencillo de cadenas

Problema 6.1. Nuestro primer problema es muy simple: Queremos contar cuántas letras “A” hay en una cadena x.

In [80]:
def contarA(x):
    """ La funcion contarA(x) cuenta cuántas
    letras "A" aparecen en la cadena x ."""
    contador = 0
    for letra in x:
        if letra == "A":
            contador = contador + 1 
    return contador

Y lo probamos

In [72]:
contarA("Ana")

1

In [74]:
contarA("banana")

0

In [76]:
contarA("lAn")

1

In [78]:
contarA("lAAn")

2

In [79]:
contarA("lAnA")

2

Ejercicio 6.5. ¿Hay más letras “A” o más letras “E” en una cadena? Escribir un programa que lo decida.

In [109]:
def masAoE(x):
    """La funcion masAoE determina si hay más letras 'A' o 'E'
    en una cadena de texto"""
    contarA = 0
    contarE = 0
    for palabra in x:
        if palabra == "A":
            contarA = contarA + 1
        elif palabra == "E":
            contarE = contarE + 1
    if contarA > contarE:
        print("Existen más letras A que E en esta cadena de caracteres")
    elif contarA < contarE: 
        print("Existen más letras E que A en esta cadena de caracteres")

In [111]:
masAoE("MARESCA")

Existen más letras A que E en esta cadena de caracteres


In [112]:
masAoE("PESQUERA")

Existen más letras E que A en esta cadena de caracteres


Ejercicio 6.6. Escribir un programa que cuente cúantas veces aparecen cada una de las vocales en una cadena. No importa si la vocal aparece en mayúscula o en minúscula.

In [137]:
def cantVocales(x):
    """La funcion cantVocales cuenta cuántas veces aparecen 
    cada una de las vocales de una cadena. No importa si la vocal aparece
    en may o min"""
    
    contarA = 0
    contarE = 0
    contarI = 0
    contarO = 0
    contarU = 0

    for palabra in x: 
        if palabra == "A" or palabra == "a":
            contarA = contarA + 1
        elif palabra == "E" or palabra == "e":
            contarE = contarE + 1
        elif palabra == "I" or palabra == "i":
            contarI = contarI + 1
        elif palabra == "O" or palabra == "o":
            contarO = contarO + 1
        elif palabra == "U" or palabra == "u":
            contarU = contarU + 1
            
    print("Cantidad de letras A: ", contarA)
    print("Cantidad de letras E: ", contarE)
    print("Cantidad de letras I: ", contarI)
    print("Cantidad de letras O: ", contarO)
    print("Cantidad de letras U: ", contarU)

In [140]:
cantVocales("parangaricutirimicuaro")

Cantidad de letras A:  4
Cantidad de letras E:  0
Cantidad de letras I:  4
Cantidad de letras O:  1
Cantidad de letras U:  2


In [141]:
cantVocales("desparangaricutirimicuarizador")

Cantidad de letras A:  5
Cantidad de letras E:  1
Cantidad de letras I:  5
Cantidad de letras O:  1
Cantidad de letras U:  2


### 6.5. Nuestro primer juego

Con todo esto ya estamos en condiciones de escribir un programa para jugar con la computadora: el Mastermind. El Mastermind es un juego que consiste en deducir un código numérico de (por ejemplo) cuatro cifras.

In [46]:
def mastermind():
    # modulo que va a permitir elegir números aleatoriamente
    import random

    # el conjunto de simbolos válidos en el código
    digitos = ('0','1','2','3','4','5','6','7','8','9')

    #"elegimos" el codigo
    codigo = ''
    for i in range(4):
        candidato = random.choice(digitos)
        #vamos eligiendo digitos no repetidos
        while candidato in codigo:
            candidato = random.choice(digitos)
        codigo = codigo + candidato
    # iniciamos interaccion con el usuario
    print("Bienvenida/o a Mastermind!")
    print("Tienes que adivinar un numero de ", 4, "Cifras distintas")
    propuesta = input("Que codigo propones?: ")

    # procesamos las propuestas e indicamos aciertos y coincidencias
    intentos = 1
    while propuesta != codigo:
        intentos = intentos +1
        aciertos = 0
        coincidencias = 0

        #recorremos la propuesta y verificaos en el codigo
        for i in range(4):
            if propuesta[i] == codigo[i]:
                aciertos = aciertos +1
            elif propuesta[i] in codigo:
                coincidencias = coincidencias +1
        print("Tu propuesta (", propuesta, ") tiene ", aciertos, "aciertos y ", coincidencias, "coincidencias.")
        #pedimos siguiente propuesta
        propuesta = input("propone otro codigo")
    print("Felicitaciones! Adivinaste el codigo en", intentos, "intentos.")
mastermind()

Bienvenida/o a Mastermind!
Tienes que adivinar un numero de  4 Cifras distintas
Que codigo propones?: 2345
Tu propuesta ( 2345 ) tiene  0 aciertos y  1 coincidencias.
propone otro codigo2346
Tu propuesta ( 2346 ) tiene  0 aciertos y  1 coincidencias.
propone otro codigo2432
Tu propuesta ( 2432 ) tiene  1 aciertos y  0 coincidencias.
propone otro codigo6534
Tu propuesta ( 6534 ) tiene  0 aciertos y  1 coincidencias.
propone otro codigo3421
Tu propuesta ( 3421 ) tiene  1 aciertos y  0 coincidencias.
propone otro codigo2450
Tu propuesta ( 2450 ) tiene  2 aciertos y  0 coincidencias.
propone otro codigo2459
Tu propuesta ( 2459 ) tiene  1 aciertos y  1 coincidencias.
propone otro codigo3490
Tu propuesta ( 3490 ) tiene  2 aciertos y  1 coincidencias.
propone otro codigo2493
Tu propuesta ( 2493 ) tiene  1 aciertos y  1 coincidencias.
propone otro codigo3450
Tu propuesta ( 3450 ) tiene  2 aciertos y  0 coincidencias.
propone otro codigo9450
Tu propuesta ( 9450 ) tiene  3 aciertos y  0 coincide

Podemos ver que para este caso el programa parece haberse comportado bien. ¿Pero cómo
podemos saber que el código final era realmente el que eligió originalmente el programa?
¿O qué habría pasado si no encontrábamos la solución?

Para probar estas cosas recurrimos a la depuración del programa. Una forma de hacerlo es
simplemente agregar algunas líneas en el código que nos informen lo que está sucediendo
que no podemos ver. Por ejemplo, los números que va eligiendo al azar y el código que
queda al final. Así podremos verificar si las respuestas son correctas a medida que las
hacemos y podremos elegir mejor las propuestas enlas pruebas.

In [1]:
def mastermind():
    # modulo que va a permitir elegir números aleatoriamente
    import random

    # el conjunto de simbolos válidos en el código
    digitos = ('0','1','2','3','4','5','6','7','8','9')

    #"elegimos" el codigo
    codigo = ''
    for i in range(4):
        candidato = random.choice(digitos)
        #vamos eligiendo digitos no repetidos
        while candidato in codigo:
            print("DEBUG: candidato =", candidato)
            candidato = random.choice(digitos)
        codigo = codigo + candidato
        print("DEBUG: el codigo va siendo= ", codigo)
        
    # iniciamos interaccion con el usuario
    print("Bienvenida/o a Mastermind!")
    print("Tienes que adivinar un numero de ", 4, "Cifras distintas")
    propuesta = input("Que codigo propones?: ")

    # procesamos las propuestas e indicamos aciertos y coincidencias
    intentos = 1
    while propuesta != codigo:
        intentos = intentos +1
        aciertos = 0
        coincidencias = 0
    
        #recorremos la propuesta y verificaos en el codigo
        for i in range(4):
            if propuesta[i] == codigo[i]:
                aciertos = aciertos +1
            elif propuesta[i] in codigo:
                coincidencias = coincidencias +1
        print("Tu propuesta (", propuesta, ") tiene ", aciertos, "aciertos y ", coincidencias, "coincidencias.")
        #pedimos siguiente propuesta
        propuesta = input("propone otro codigo: ")
    print("Felicitaciones! Adivinaste el codigo en", intentos, "intentos.")
mastermind()

DEBUG: el codigo va siendo=  5
DEBUG: el codigo va siendo=  57
DEBUG: el codigo va siendo=  571
DEBUG: el codigo va siendo=  5710
Bienvenida/o a Mastermind!
Tienes que adivinar un numero de  4 Cifras distintas
Que codigo propones?: 2310
Tu propuesta ( 2310 ) tiene  2 aciertos y  0 coincidencias.
propone otro codigo: 6710
Tu propuesta ( 6710 ) tiene  3 aciertos y  0 coincidencias.
propone otro codigo: 5710
Felicitaciones! Adivinaste el codigo en 3 intentos.


Mantenimiento: Supongamos que queremos jugar el mismo juego, pero en lugar de hacerlo
con un número de cuatro cifras, adivinar uno de cinco. ¿Qué tendríamos que hacer
para cambiarlo?

Para empezar, habría que reemplazar el 4 en la línea 11 del programa por un 5, indicando
que hay que elegir 5 dígitos al azar. Pero además, el ciclo en la línea 31 también necesita
cambiar la cantidad de veces que se va a ejecutar, 5 en lugar de 4. Y hay un lugar más,
adentro del mensaje al usuario que indica las instrucciones del juego en la línea 20.

El problema de ir cambiando estos números de a uno es que si quisiéramos volver al
programa de los 4 dígitos o quisiéramos cambiarlo por uno que juegue con 3, tenemos que volver a hacer los reemplazos en todos lados cada vez que lo queremos cambiar, y
corremos el riesgo de olvidarnos de alguno e introducir errores en el código.

Una forma de evitar esto es fijar la cantidad de cifras en una variable y cambiarla sólo ahí:

In [ ]:
def mastermind():
    # modulo que va a permitir elegir números aleatoriamente
    import random

    # el conjunto de simbolos válidos en el código
    digitos = ('0','1','2','3','4','5','6','7','8','9')

    #"elegimos" el codigo
    cant_digitos = 5
    codigo = ''
    for i in range(cant_digitos):
        candidato = random.choice(digitos)
        #vamos eligiendo digitos no repetidos
        while candidato in codigo:
            candidato = random.choice(digitos)
        codigo = codigo + candidato
    # iniciamos interaccion con el usuario
    print("Bienvenida/o a Mastermind!")
    print("Tienes que adivinar un numero de ", cant_digitos, "Cifras distintas")
    propuesta = input("Que codigo propones?: ")

    # procesamos las propuestas e indicamos aciertos y coincidencias
    intentos = 1
    while propuesta != codigo:
        intentos = intentos +1
        aciertos = 0
        coincidencias = 0

        #recorremos la propuesta y verificaos en el codigo
        for i in range(cant_digitos):
            if propuesta[i] == codigo[i]:
                aciertos = aciertos +1
            elif propuesta[i] in codigo:
                coincidencias = coincidencias +1
        print("Tu propuesta (", propuesta, ") tiene ", aciertos, "aciertos y ", coincidencias, "coincidencias.")
        #pedimos siguiente propuesta
        propuesta = input("propone otro acodigo")
    print("Felicitaciones! Adivinaste el codigo en", intentos, "intentos.")
mastermind()

Con 5 dígitos, el juego se pone más difícil. Nos damos cuenta que si el jugador no logra
adivinar el código, el programa no termina: se queda preguntando códigos y respondiendo
aciertos y coincidencias para siempre. Entonces queremos darle al usuario la posibilidad
de rendirse y saber cuál era la respuesta y terminar el programa.

Para esto agregamos en el ciclo while principal una condición extra: para seguir preguntando,
la propuesta tiene que ser distinta al código pero además tiene que ser distinta del
texto "Me doy".

In [3]:
def mastermind():
    # modulo que va a permitir elegir números aleatoriamente
    import random

    # el conjunto de simbolos válidos en el código
    digitos = ('0','1','2','3','4','5','6','7','8','9')

    #"elegimos" el codigo
    cant_digitos = 5
    codigo = ''
    for i in range(cant_digitos):
        candidato = random.choice(digitos)
        #vamos eligiendo digitos no repetidos
        while candidato in codigo:
            candidato = random.choice(digitos)
        codigo = codigo + candidato
    # iniciamos interaccion con el usuario
    print("Bienvenida/o a Mastermind!")
    print("Tienes que adivinar un numero de ", cant_digitos, "Cifras distintas")
    propuesta = input("Que codigo propones?: ")

    # procesamos las propuestas e indicamos aciertos y coincidencias
    intentos = 1
    while propuesta != codigo and propuesta != "Me doy":
        intentos = intentos +1
        aciertos = 0
        coincidencias = 0

        #recorremos la propuesta y verificaos en el codigo
        for i in range(cant_digitos):
            if propuesta[i] == codigo[i]:
                aciertos = aciertos +1
            elif propuesta[i] in codigo:
                coincidencias = coincidencias +1
        print("Tu propuesta (", propuesta, ") tiene ", aciertos, "aciertos y ", coincidencias, "coincidencias.")
        #pedimos siguiente propuesta
        propuesta = input("propone otro acodigo")
        
    if propuesta == "Me doy":
        print("El codigo era:", codigo)
        print("Suerte la proxima vez!")
    else: 
        print("Felicitaciones!, Adivinaste el codigo en ", intentos, "intentos.")
mastermind()

Bienvenida/o a Mastermind!
Tienes que adivinar un numero de  5 Cifras distintas
Que codigo propones?: 25632
Tu propuesta ( 25632 ) tiene  0 aciertos y  2 coincidencias.
propone otro acodigoMe doy
El codigo era: 67158
Suerte la proxima vez!


### 7. Tuplas y listas

Python cuenta con una gran variedad de tipos de datos que permiten representar la información según cómo esté estructurada. En esta unidad se estudian las tuplas y las listas, que son tipos de datos utilizados cuando se quiere agrupar elementos.

### 7.1 Tuplas

En programación, en general, al querer modelar objetos de la vida real, es muy común que querramos describir un objeto como un agrupamiento de datos de distintos tipos. Veamos algunos ejemplos:

Una fecha la podemos querer representar como la terna día (un número entero), mes(una cadena de caracteres), y año (un número entero), y tendremos por ejemplo: (25, "Mayo", 1810).

Como datos de los alumnos queremos guardar número de padrón, nombre y apellido, como por ejemplo (89766, "Alicia", "Hacker").

Es posible anidar tuplas: como datos de los alumnos queremos guardar número de padrón, nombre, apellido y fecha de nacimiento, como por ejemplo: (89766, "Alicia", "Hacker", (9, "Julio", 1988)).

### 7.1.1. Elementos y segmentos de tuplas

Las tuplas son secuencias, igual que las cadenas, y se puede utilizar la misma notación de índices que en las cadenas para obtener cada una de sus componentes.

El primer elemento de (25, "Mayo", 1810) es 25.

El segundo elemento de (25, "Mayo", 1810) es “Mayo”.

El tercer elemento de (25, "Mayo", 1810) es 1810.

In [8]:
t=(25,"Mayo",1810)

In [9]:
t[0]

25

In [10]:
t[1]

'Mayo'

In [12]:
t[2]

1810

Ejercicio 7.1. ¿Cuál es el cuarto elemento de (89766, "Alicia", "Hacker", (9, "Julio", 1988))?

In [13]:
r=(89766, "Alicia", "Hacker", (9, "Julio", 1988))

In [18]:
r[3]

(9, 'Julio', 1988)

### 7.1.2. Las tuplas son inmutables

Al igual que con las cadenas, las componentes de las tuplas no pueden ser modificadas:

In [17]:
t[2]= 2008

TypeError: 'tuple' object does not support item assignment

### 7.1.3. Longitud de tuplas

A las tuplas también se les puede aplicar la función len() para calcular su longitud. El valor de esta función aplicada a una tupla nos indica cuántas componentes tiene esa tupla.

In [20]:
len(t)

3

Ejercicio 7.2. ¿Cuál es la longitud de (89766, "Alicia", "Hacker", (9, "Julio", 1988))?

In [21]:
len(r)

4

Una tupla vacía es una tupla con 0 componentes, y se la indica como ().

In [22]:
z=()
len(z)

0

Una tupla unitaria es una tupla con una componente. Para distinguir la tupla unitaria de la
componente que contiene, Python exige que a la componente no sólo se la encierre entre
paréntesis sino que se le ponga una coma a continuación del valor de la componente (así
(1810) es un número, pero (1810,) es la tupla unitaria cuya única componente vale
1810).

In [25]:
u=(1810,)
len(u)

1

### 7.1.4. Empaquetado y desempaquetado de tuplas

Si a una variable se le asigna una secuencia de valores separados por comas, el valor de esa
variable será la tupla formada por todos los valores asignados. A esta operación se la denomina
empaquetado de tuplas.

In [29]:
a=125
b="#"
c="Ana"
d=a,b,c

In [30]:
len(d)

3

In [32]:
d

(125, '#', 'Ana')

Si se tiene una tupla de longitud k, se puede asignar la tupla a k variables distintas y en
cada variable quedará una de las componentes de la tupla. A esta operación se la denomina
desempaquetado de tuplas.

In [33]:
x,y,z=d

In [35]:
x

125

In [36]:
y

'#'

In [37]:
z

'Ana'

### 7.2. Listas

Presentaremos ahora una nueva estructura de datos: la lista. Usaremos listas para poder modelar
datos compuestos pero cuya cantidad y valor varían a lo largo del tiempo. Son secuencias
mutables y vienen dotadas de una variedad de operaciones muy útiles.

La notación para lista es una secuencia de valores encerrados entre corchetes y separados
por comas. Por ejemplo, si representamos a los alumnos mediante su número
de padrón, se puede tener una lista de inscriptos en la materia como la siguiente: i
[78455, 89211, 66540, 45750]. Al abrirse la inscripción, antes de que hubiera inscriptos,
la lista de inscriptos se representará por una lista vacía: [].

### 7.2.1. Longitud de la lista. Elementos y segmentos de listas

Como a las secuencias ya vistas, a las listas también se les puede aplicar la función len()
para conocer su longitud.

Para acceder a los distintos elementos de la lista se utilizará la misma notación de índices
de cadenas y tuplas, con valores que van de 0 a la longitud de la lista -1.

In [2]:
xs=[78455, 89211, 66540, 45750]

In [41]:
xs[0]

78455

In [42]:
len(xs)

4

Para obtener una sublista a partir de la lista original, se utiliza la notación de rangos, como en las otras secuencias.

Para obtener la lista que contiene sólo a quién se inscribió en segundo lugar podemos
escribir:

In [44]:
xs[1:2]

[89211]

Para obtener la lista que contiene al segundo y tercer inscriptos podemos escribir:

In [45]:
xs[1:3]

[89211, 66540]

Para obtener la lista que contiene al primero y segundo inscriptos podemos escribir:

In [46]:
xs[0:2]

[78455, 89211]

### 7.2.2. Cómo mutar listas

Dijimos antes que las listas son secuencias mutables. Para lograr la mutabilidad Python provee operaciones que nos permiten cambiarle valores, agregarle valores y quitarle valores.

Para cambiar una componente de una lista, se selecciona la componente mediante su
índice y se le asigna el nuevo valor:

In [3]:
xs[1]=79211

In [4]:
xs

[78455, 79211, 66540, 45750]

Para agregar un nuevo valor al final de la lista se utiliza la operación append(). Escribimos
xs.append(47890) para agregar el padrón 47890 al final de xs.

In [6]:
xs.append(47890)

In [7]:
xs

[78455, 79211, 66540, 45750, 47890, 47890]

Para insertar un nuevo valor en la posición cuyo índice es k (y desplazar un lugar el resto
de la lista) se utiliza la operación insert().

Escribimos xs.insert(2, 54988) para insertar el padrón 54988 en la tercera posición
de xs.

In [9]:
xs.insert(2, 54988)

In [10]:
xs

[78455, 79211, 54988, 66540, 45750, 47890, 47890]

In [11]:
xs.insert(1,78455)

In [12]:
xs

[78455, 78455, 79211, 54988, 66540, 45750, 47890, 47890]

Para eliminar un valor de una lista se utiliza la operación remove().
Escribimos xs.remove(45750) para borrar el padrón 45750 de la lista de inscriptos:

In [13]:
xs.remove(45750)

In [14]:
xs

[78455, 78455, 79211, 54988, 66540, 47890, 47890]

Si el valor a borrar está repetido, se borra sólo su primera aparición:

In [16]:
xs.remove(78455)

In [17]:
xs

[78455, 79211, 54988, 66540, 47890, 47890]

### 7.2.3. Cómo buscar dentro de las listas

Queremos poder formular dos preguntas más respecto de la lista de inscriptos:

¿Está la persona cuyo padrón es v inscripta en esta materia?

¿En qué orden se inscribió la persona cuyo padrón es v?.

Veamos qué operaciones sobre listas se pueden usar para lograr esos dos objetivos:

Para preguntar si un valor determinado es un elemento de una lista usaremos la operación
in:

In [23]:
xs

[78455, 79211, 54988, 66540, 47890, 47890]

In [24]:
78 in xs

False

In [25]:
66540 in xs

True

In [26]:
### Esta operación se puede utilizar para todas las secuencias, incluyendo tuplas y cadenas

Para averiguar la posición de un valor dentro de una lista usaremos la operación
index().

In [27]:
xs.index(78455)

0

In [28]:
xs.index(47890)

4

Si el valor está repetido, el índice que devuelve es el de la primera aparición:

In [29]:
ys = [10,20,10]
ys.index(10)

0

Para iterar sobre todos los elementos de una lista usaremos una construcción for:

In [33]:
zs = [5,3,8,10,2]
for x in zs:
    print(x)

5
3
8
10
2


Problema 7.1. Queremos escribir un programa que nos permita armar la lista de los inscriptos
de una materia.

In [47]:
def inscripcion():
    """ Módulo para inscribir alumnos al curso - versión 0 """
    #Iniciamos la interaccion con el usuario
    print("Incripcion en el curso 04 de 75.40")
    
    #Leemos el primer padrón
    padron = int(input("Ingresa un padrón(<=0 para terminar): "))
    
    #Procesamos los padrones
    #Inicialmente no hay inscritos
    ins= []
    while padron > 0:
        #Agregamos el padrón leído a la lista de inscritos
        ins.append(padron)
        
        #Leemos otro padrón más
        padron = int(input("Ingresa un padrón(<=0 para terminar): "))
    #Mostramos el resultado
    print("Esta es la lista de inscritos: ", ins)

In [48]:
inscripcion()

Incripcion en el curso 04 de 75.40
Ingresa un padrón(<=0 para terminar): 30
Ingresa un padrón(<=0 para terminar): 40
Ingresa un padrón(<=0 para terminar): 50
Ingresa un padrón(<=0 para terminar): 0
Esta es la lista de inscritos:  [30, 40, 50]


In [49]:
inscripcion()

Incripcion en el curso 04 de 75.40
Ingresa un padrón(<=0 para terminar): 30
Ingresa un padrón(<=0 para terminar): 40
Ingresa un padrón(<=0 para terminar): 40
Ingresa un padrón(<=0 para terminar): 30
Ingresa un padrón(<=0 para terminar): 50
Ingresa un padrón(<=0 para terminar): 0
Esta es la lista de inscritos:  [30, 40, 40, 30, 50]


Evidentemente el programa funciona de acuerdo a lo especificado, pero hay algo que no
tuvimos en cuenta: permite inscribir a una misma persona más de una vez.

Mantenimiento: No permitir que haya padrones repetidos.

In [2]:
def inscripcion():
    """ Módulo para inscribir alumnos al curso - versión 1 """
    # Iniciamos la interacción con el usuario
    print("Inscripcion en el curso 04 de 75.40")
    
    # Leemos el primer padrón
    padron=int(input("Ingresa un padrón (<=0 para terminar): "))
    
    # Procesamos los padrones
    # Inicialmente no hay inscritos
    ins = []
    while padron > 0:
        # Si todavía no está, agregamos el padrón a la lista de inscriptos
        if padron not in ins:
            ins.append(padron)
        # de lo contrario avisamos que ya figura
        else:
            print("ya figura en la lista")
        
        #Leemos otro padrón más
        padron=int(input("Ingresa un padrón (<=0 para terminar): "))
    
    #Mostramos el resultado
    print("Esta es la lista de inscritos: ", ins)
        
inscripcion()

Inscripcion en el curso 04 de 75.40
Ingresa un padrón (<=0 para terminar): 30
Ingresa un padrón (<=0 para terminar): 40
Ingresa un padrón (<=0 para terminar): 40
ya figura en la lista
Ingresa un padrón (<=0 para terminar): 30
ya figura en la lista
Ingresa un padrón (<=0 para terminar): 50
Ingresa un padrón (<=0 para terminar): 0
Esta es la lista de inscritos:  [30, 40, 50]


Pero ahora el resultado es satisfactorio: no tenemos inscriptos repetidos.

### 7.3. Ordenar listas

Para dejar la lista original intacta pero obtener una nueva lista ordenada a partir de ella,
se usa la función sorted.

In [6]:
bs=[5,2,4,2]
cs = sorted(bs)

In [8]:
bs

[5, 2, 4, 2]

In [9]:
cs

[2, 2, 4, 5]

### 7.4. Listas y cadenas

A partir de una cadena de caracteres, podemos obtener una lista con sus componentes usando
la función split.

Si queremos obtener las palabras (separadas entre sí por espacios) que componen la cadena
xs escribiremos simplemente xs.split():

In [11]:
c = " Una cadena con espacios "

In [12]:
c

' Una cadena con espacios '

In [14]:
c.split()

['Una', 'cadena', 'con', 'espacios']

En este caso split elimina todos los blancos de más, y devuelve sólo las palabras que
conforman la cadena.

Si en cambio el separador es otro carácter (por ejemplo la arroba, "@"), se lo debemos pasar
como parámetro a la función split. En ese caso se considera una componente todo lo que se
encuentra entre dos arrobas consecutivas. En el caso particular de que el texto contenga dos
arrobas una a continuación de la otra, se devolverá una componente vacía:

In [19]:
d="@@Una@@cadena@@@con@@arrobas@"

In [33]:
d.split("@")

['', '', 'Una', '', 'cadena', '', '', 'con', '', 'arrobas', '']

In [34]:
a="@Una@@cadena@@@de@@@@caracteres"
a.split("@")

['', 'Una', '', 'cadena', '', '', 'de', '', '', '', 'caracteres']

La “casi”–inversa de split es una función join que tiene la siguiente sintaxis:

In [ ]:
<separador>.join( <lista de componentes a unir>)

y que devuelve la cadena que resulta de unir todas las componentes separadas entre sí por
medio del separador:

In [1]:
xs = ['aaa', 'bbb', 'cccc']

In [23]:
xs

['aaa', 'bbb', 'cccc']

In [24]:
" ".join(xs)

'aaa bbb cccc'

In [25]:
", ".join(xs)

'aaa, bbb, cccc'

In [2]:
"@@".join(xs)

'aaa@@bbb@@cccc'

### 8. Algoritmos de búsqueda

### 8.1 El problema de la búsqueda

Presentamos ahora uno de los problemas más clásicos de la computación, el problema de la
búsqueda, que se puede enunciar de la siguiente manera:

Problema: Dada una lista xs y un valor x devolver el índice de x en xs si x está en xs, y -1
si x no está en xs.

Alicia Hacker afirma que este problema tiene una solución muy sencilla en Python: se puede
usar directamente la poderosa función index() de lista.

Probamos esa solución para ver qué pasa:

In [1]:
[1,3,5,7].index(5)

2

In [2]:
[1,3,5,7].index(20)

ValueError: 20 is not in list

Vemos que usar la función index() resuelve nuestro problema si el valor buscado está en
la lista, pero si el valor no está no sólo no devuelve un 􀀀1, sino que se produce un error.
El problema es que para poder aplicar la función index() debemos estar seguros de que
el valor está en la lista, y para averiguar eso Python nos provee del operador in:

In [3]:
5 in [1,3,5,7]

True

In [4]:
20 in [1,3,5,7]

False

O sea que si llamamos a la función index() sólo cuando el resultado de in es verdadero,
y devolvemos -1 cuando el resultado de in es falso, estaremos resolviendo el problema planteado
usando sólo funciones provistas por Python. La solución se muestra en el Código 8.1.

In [26]:
def busqueda_con_index(xs, x):
    """Busca un elemento x en una lista xs
    
    si x está en xs devuelve xs.index(x)
    de lo contrario devuelve -1
    """
    
    if x in xs:
        return(xs.index(x))
    else:
        return(-1)

In [27]:
busqueda_con_index([1, 4, 54, 3, 0, -1], 3)

3

In [28]:
busqueda_con_index([1, 4, 54, 3, 0, -1], 44)

-1

In [29]:
busqueda_con_index([], 0)

-1


### ¿Cuántas comparaciones hace este programa?

La pregunta del título se refiere a ¿cuánto esfuerzo computacional requiere este programa?,
¿cuántas veces compara el valor que buscamos con los datos de la lista? No lo sabemos porque
no sabemos cómo están implementadas las funciones in e index(). La pregunta queda
planteada por ahora pero daremos un método para averiguarlo más adelante en esta unidad.

### 8.2. Cómo programar la búsqueda lineal a mano

No interesa ver qué sucede si programamos la búsqueda usando operaciones más elementales,
y no las grandes primitivas in e index(). Esto nos permitirá estudiar una solución que
puede portarse a otros lenguajes que no tienen instrucciones tan poderosas.

Supongamos entonces que nuestra versión de Python no existen ni in ni index(). Podemos
en cambio acceder a cada uno de los elementos de la lista a través de una construcción
for, y también, por supuesto, podemos acceder a un elemento de la lista mediante un índice.

### 8.3. Búsqueda lineal

Diseñamos una solución: Podemos comparar uno a uno los elementos de la lista con el valor
de x, y retornar el valor de la posición donde lo encontramos en caso de encontrarlo.

Si llegamos al final de la lista sin haber salido antes de la función es porque el valor de x no
está en la lista, y en ese caso retornamos -1.

En esta solución necesitamos una variable i que cuente en cada momento en qué posición
de la lista estamos parados. Esta variable se inicializa en 0 antes de entrar en el ciclo y se
incrementa en 1 en cada paso.

In [20]:
def busqueda_lineal(lista,x):
    """Busqueda lineal
       Si x está en la lista devuelve su posición en lista, de lo contrario devuelve -1.
    """
    # Estrategia: se recorren uno a uno los elementos de la lista
    # y se los compara con el valor x buscado.
    i=0 #tiene la posicion actual de la lista, inicializa en 0
    
    #el ciclo for recorre todos los elementos de lista:
    for z in lista:
        # estamos en la posicion i, z contiene el valor de lista[i]
        # si z es igual a x, devuelve i
        if z == x: 
            return i
        
        #si z es distinto de x, incremente i, y continúa el ciclo
        i=i+1
        
    #si salió del ciclo sin haber encontrado el valor, devuelve -1
    return -1

Y ahora lo probamos:

In [22]:
busqueda_lineal([1,4,54,3,0,-11],44)

-1

In [23]:
busqueda_lineal([1, 4, 54, 3, 0, -1], 3)

3

In [24]:
busqueda_lineal([1, 4, 54, 3, 0, -1], 0)

4

In [25]:
busqueda_lineal([],0)

-1

### 9. Diccionarios

En esta unidad analizaremos otro tipo de dato importante: los diccionarios. Su importancia,
radica no sólo en las grandes posibilidades que presentan como estructuras para almacenar
información, sino también en que, en Python, son utilizados por el propio lenguaje para realizar
diversas operaciones y para almacenar información de otras estructuras.

### 9.1. Qué es un diccionario

En Python, un diccionario es una colección no-ordenada de valores que son accedidos a
traves de una clave. Es decir, en lugar de acceder a la información mediante el índice numérico,
como es el caso de las listas y tuplas, es posible acceder a los valores a través de sus claves, que
pueden ser de diversos tipo.

Las claves son únicas dentro de un diccionario, es decir que no puede haber un diccionario
que tenga dos veces la misma clave, si se asigna un valor a una clave ya existente, se reemplaza
el valor anterior.

No hay una forma directa de acceder a una clave a través de su valor, y nada impide que
un mismo valor se encuentre asignado a distintas claves

La informacion almacenada en los diccionarios, no tiene un orden particular. Ni por clave
ni por valor, ni tampoco por el orden en que han sido agregados al diccionario.

Cualquier variable de tipo inmutable, puede ser clave de un diccionario: cadenas, enteros,
tuplas (con valores inmutables en sus miembros), etc. No hay restricciones para los valores que
el diccionario puede contener, cualquier tipo puede ser el valor: listas, cadenas, tuplas, otros
diccionarios, objetos, etc.

### 9.2. Utilizando diccionarios en Python

De la misma forma que con listas, es posible definir un diccionario directamente con los
miembros que va a contener, o bien inicializar el diccionario vacío y luego agregar los valores
de a uno o de a muchos.

Para definirlo junto con los miembros que va a contener, se encierra el listado de valores
entre llaves, las parejas de clave y valor se separan con comas, y la clave y el valor se separan
con ’:’.

In [9]:
punto = { 'x':2, 'y':1, 'z':4 }

In [8]:
punto

{'y': 1, 'z': 4}

Para declararlo vacío y luego ingresar los valores, se lo declara como un par de llaves sin
nada en medio, y luego se asignan valores directamente a los índices.

In [5]:
materias = {}

In [6]:
materias["lunes"] = [6103, 7540]

In [7]:
materias["martes"] = [6201]

In [8]:
materias["miercoles"] = [6103, 7540]

In [9]:
materias["jueves"] = []

In [10]:
materias["viernes"] = [6201]

Para acceder al valor asociado a una determinada clave, se lo hace de la misma forma que
con las listas, pero utilizando la clave elegida en lugar del índice.

In [12]:
print (materias["lunes"])

[6103, 7540]


Sin embargo, esto falla si se provee una clave que no está en el diccionario. Es posible,
por otro lado, utilizar la función get, que devuelve el valor None si la clave no está en el
diccionario, o un valor por omisión que se establece opcionalmente.

In [18]:
print(materias["domingo"])

KeyError: 'domingo'

In [17]:
print(materias.get("domingo"))

None


In [24]:
print (materias.get("domingo", []))

[]


Existen diversas formas de recorrer un diccionario. Es posible recorrer sus claves y usar esas
claves para acceder a los valores.

In [27]:
for dia in materias:
    print(dia, ":", materias[dia])

lunes : [6103, 7540]
martes : [6201]
miercoles : [6103, 7540]
jueves : []
viernes : [6201]


Es posible, también, obtener los valores como tuplas donde el primer elemento es la clave
y el segundo el valor

In [31]:
for dia, codigos in materias.items():
    print(dia, ":", codigos)

lunes : [6103, 7540]
martes : [6201]
miercoles : [6103, 7540]
jueves : []
viernes : [6201]


Para verificar si una clave se encuentra en el diccionario, es posible utilizar la palabra reservada in.

In [66]:
d = {'x': 12, 'y': 7}  

In [67]:
if 'y' in d:
    print (d['y']) # Imprime 7

7


Más allá de la creación y el acceso, hay muchas otras operaciones que se pueden realizar
sobre los diccionarios, para poder manipular la información según sean nuestras necesidades,
algunos de estos métodos pueden verse en la referencia al final de la unidad

No es posible obtener porciones de un diccionario usando [:], ya que al no tener un orden
determinado para los elementos, no sería posible tomarlos en orden.

### 10. Contratos y Mutabilidad

### 10.1. Pre y Postcondiciones

Cuando hablamos de contratos o programación por contratos, nos referimos a la necesidad de
estipular tanto lo que necesita como lo que devuelve nuestro código.

Las condiciones que deben estar dadas para que el código funcione las llamamos precondiciones
y las condiciones sobre el estado en que quedan las variables y él o los valores de retorno,
las llamamos postcondiciones.

Esta estipulación es mayormente para que la utilicen otros programadores, por lo que es
particularmente útil cuando se encuentra dentro de la documentación. En ciertos casos, además,
puede quererse que el programa revise si las condiciones realmente se cumplen y de no
ser así, actúe en consecuencia.

Existen herramientas en algunos lenguajes de programación que facilitan estas acciones, en
el caso de Python, es posible utilizar la instrucción assert.

### 10.1.1. Precondiciones

Las precondiciones son las condiciones que deben cumplir los parámetros que una función
recibe, para que esta se comporte correctamente.

Por ejemplo, en una función división las precondiciones son que los parámetros son números,
y que el divisor sea distinto de 0. Tener una precondición permite asumir desde el código
que no es necesario lidiar con los casos en que las precondiciones no se cumplen.

### 10.1.2. Postcondiciones

Las postcodiciones son las condiciones que cumplirá el valor de retorno, y los parámetros
recibidos, en caso de que hayan sido alterados, siempre que se hayan cumplido las precondiciones.

En el ejemplo anterior, la función división con las precondiciones asignadas, puede asegurar
que devolverá un número correspondiente al cociente solicitado.

### 10.1.3. Aseveraciones

Tanto las precondiciones como las postcondiciones son aseveraciones (en inglés assert). Es
decir, afirmaciones realizadas en un momento particular de la ejecución sobre el estado computacional.
Si llegaran a ser falsas significaría que hay algún error en el diseño o utilización del
algoritmo.

Para comprobar estas afirmaciones desde el código en algunos casos podemos utilizar la
instrucción assert, está instrucción recibe una condición a verificar y, opcionalmente, un mensaje
de error que devolverá en caso que la condición no se cumpla.

### 10.1.4. Ejemplos

Usando los ejemplos anteriores, la función division nos quedaría de la siguiente forma:

In [17]:
def division(dividendo, divisor):
    """ Calculo de la división
    Pre: Recibe dos números, divisor debe ser distinto de 0.
    Post: Devuelve un número real, con el cociente de ambos.
    """
    assert divisor != 0, "El divisor no puede ser 0"
    return dividendo / ( divisor * 1.0 )

In [18]:
division(24,2)

12.0

In [19]:
division(12,0)

AssertionError: El divisor no puede ser 0

Otro ejemplo, tal vez más interesante, puede ser una función que implemente una sumatoria. En este caso hay que analizar cuáles van a ser los parámetros que recibirá
la función, y las precondiciones que estos parámetros deberán cumplir.
La función sumatoria a escribir, necesita de un valor inicial, un valor final, y una función a
la cual llamar en cada paso. Es decir que recibe tres parámetros.

In [48]:
def sumatoria(inicial, final):
    """Calcula la sumatoria desde i=inicial hasta final de f(i)
    Pre: inicial y final son números enteros, f es una función que
    recibe un entero y devuelve un número.
    Post: Se devuelve el valor de la sumatoria de aplicar f a cada
    número comprendido entre inicial y final.
    """
    sumatoria =int(0)
    
    if inicial < final:
        for x in range(inicial, final+1):
            sumatoria = x+sumatoria
        return sumatoria
    else:
        assert inicial<final, "El valor final no puede ser menor al inicial"
        
    

In [53]:
sumatoria(1,5)

15

### 10.2. Invariantes de ciclo

Los invariantes se refieren a estados o situaciones que no cambian dentro de un contexto
o porción de código. Hay invariantes de ciclo, que son los que veremos a continuación, e
invariantes de estado, que se verán más adelante.

El invariante de ciclo permite conocer cómo llegar desde las precondiciones hasta las postcondiciones.
El invariante de ciclo es, entonces, una aseveración que debe ser verdadera al
comienzo de cada iteración.

Por ejemplo, si el problema es ir desde el punto A al punto B, las precondiciones dicen que
estamos parados en A y las postcondiciones que estamos parados en B, un invariante podría
ser “estamos en algún punto entre A y B, en el punto más cercano a B que estuvimos hasta
ahora.”.

Más específicamente, si analizamos el ciclo para buscar el máximo en una lista desordenada,
la precondición es que la lista contiene elementos que son comparables y la postcondición es
que se devuelve el elemento máximo de la lista.

In [8]:
lista=[10,20,30,40,50,60]

In [3]:
def maximo(lista):
    "Devuelve el elemento máximo de la lista o None si está vacía."
    if not len(lista):
        return None
    max_elem = lista[0]
    for elemento in lista:
        if elemento > max_elem:
            max_elem = elemento
    return max_elem

In [4]:
maximo(lista)

60

En este caso, el invariante del ciclo es que max_elem contiene el valor máximo de la porción
de lista analizada.

Los invariantes son de gran importancia al momento de demostrar que un algoritmo funciona,
pero aún cuando no hagamos una demostración formal es muy útil tener los invariantes
a la vista, ya que de esta forma es más fácil entender cómo funciona un algoritmo y encontrar
posibles errores.

Los invariantes, además, son útiles a la hora de determinar las condiciones iniciales de
un algoritmo, ya que también deben cumplirse para ese caso. Por ejemplo, consideremos el
algoritmo para obtener la potencia n de un número.

In [4]:
def potencia(b,n):
    "Devuelve la potencia n del numero b, con n entero mayor que 0"
    p=1
    for i in range(n):
        p*=b
    return p

In [5]:
potencia(2,3)

8

En este caso, el invariante del ciclo es que la variable p contiene el valor de la potencia
correspondiente a esa iteración. Teniendo en cuenta esta condición, es fácil ver que p debe
comenzar el ciclo con un valor de 1, ya que ese es el valor correspondiente a p0.

De la misma manera, si la operación que se quiere realizar es sumar todos los elementos de
una lista, el invariante será que una variable suma contenga la suma de todos los elementos ya
recorridos, por lo que es claro que este invariante debe ser 0 cuando aún no se haya recorrido
ningún elemento.

In [6]:
def suma(lista):
    "Devuelve la suma de todos los elementos de la lista."
    suma=0
    for elemento in lista:
        suma += elemento
    return suma

In [10]:
suma(lista)

210

### 10.2.1. Comprobación de invariantes desde el código

Cuando la comprobación necesaria para saber si seguimos “en camino” es simple, se la
puede tener directamente dentro del código. Evitando seguir avanzando con el algoritmo si se
produjo un error crítico.

Por ejemplo, en una búsqueda binaria, el elemento a buscar debe ser mayor que el elemento
inicial y menor que el elemento final, de no ser así, no tiene sentido continuar con la búsqueda.
Es posible, entonces, agregar una instrucción que compruebe esta condición y de no ser cierta
realice alguna acción para indicar el error, por ejemplo, utilizando la instrucción assert, vista
anteriormente.

### 10.3. Mutabilidad e Inmutabilidad

Hasta ahora cada vez que estudiamos un tipo de variables indicamos si son mutables o
inmutables

Cuando una variable es de un tipo inmutable, como por ejemplo una cadena, es posible
asignar un nuevo valor a esa variable, pero no es posible modificar su contenido.

In [12]:
a="ejemplo"

In [13]:
a="otro"

In [14]:
a[2]="c"

TypeError: 'str' object does not support item assignment

Esto se debe a que cuando se realiza una nueva asignación, no se modifica la cadena en sí,
sino que la variable a pasa a apuntar a otra cadena. En cambio, no es posible asignar un nuevo
caracter en una posición, ya que esto implicaría modificar la cadena inmutable.

En el caso de los parámetros mutables, la asignación tiene el mismo comportamiento, es
decir que las variables pasan a apuntar a un nuevo valor.

In [3]:
lista1 = [10, 20, 30]

In [4]:
lista2 = lista1

In [5]:
lista1 = [3,5,7]

In [6]:
lista1

[3, 5, 7]

In [7]:
lista2

[10, 20, 30]

Algo importante a tener en cuenta en el caso de las variables de tipo mutable es que si hay
dos o más variables que apuntan a un mismo dato, y este dato se modifica, el cambio se ve
reflejado en ambas variables.

In [9]:
lista1 = [1,2,3]

In [10]:
lista2 = lista1

In [11]:
lista2[1]=5

In [12]:
lista1

[1, 5, 3]

In [13]:
lista2

[1, 5, 3]

### 10.3.1. Parámetros mutables e inmutables

Las funciones reciben parámetros que pueden ser mutables o inmutables.

Si dentro del cuerpo de la función se modifica uno de estos parámetros para que apunte
a otro valor, este cambio no se verá reflejado fuera de la función. Si, en cambio, se modifica el contenido de alguno de los parámetros mutables, este cambio sí se verá reflejado fuera de la
función.

A continuación un ejemplo en el cual se asigna la variable recibida, a un nuevo valor. Esa
asignación sólo tiene efecto dentro de la función.

In [48]:
def no_cambia_lista(lista):
    lista = list(range(len(lista)))
    print(lista)

In [49]:
lista=[10,20,30,40]

In [50]:
no_cambia_lista(lista)

[0, 1, 2, 3]


In [51]:
lista

[10, 20, 30, 40]

A continuación un ejemplo en el cual se modifica la variable recibida. En este caso, los
cambios realizados tienen efecto tanto dentro como fuera de la función.

In [26]:
def cambia_lista(lista):
    for i in range(len(lista)):
        lista[i]=lista[i]**3

In [28]:
lista = [1,2,3,4]

In [30]:
cambia_lista(lista)

In [31]:
lista

[1, 8, 27, 64]

### Unidad 11 Manejo de archivos

Veremos en esta unidad cómo manejar archivos desde nuestros programas.

Existen dos formas básicas de acceder a un archivo, una es utilizarlo como un archivo de
texto, que procesaremos línea por línea; la otra es tratarlo como un archivo binario, que procesaremos
byte por byte.

En Python, para abrir un archivo usaremos la función open, que recibe el nombre del archivo
a abrir.

In [ ]:
archivo = open("archivo.txt")

Esta función intentará abrir el archivo con el nombre indicado. Si tiene éxito, devolverá una
variable que nos permitirá manipular el archivo de diversas maneras.

La operación más sencilla a realizar sobre un archivo es leer su contenido. Para procesarlo
línea por línea, es posible hacerlo de la siguiente forma:

In [ ]:
linea=archivo.readline()
while linea != '':
    # procesar linea
    linea=archivo.readline()

Esto funciona ya que cada archivo que se encuentre abierto tiene una posición asociada,
que indica el último punto que fue leído. Cada vez que se lee una línea, avanza esa posición.

Es por ello que readline() devuelve cada vez una línea distinta y no siempre la misma.

La siguiente estructura es una forma equivalente a la vista en el ejemplo anterior.

In [ ]:
for linea in archivo:
# procesar linea

De esta manera, la variable linea irá almacenando distintas cadenas correspondientes a
cada una de las líneas del archivo.

Es posible, además, obtener todas las líneas del archivo utilizando una sola llamada a función:

In [ ]:
lineas = archivo.readlines()

### 11.1 Cerrar un archivo

Al terminar de trabajar con un archivo, es recomendable cerrarlo, por diversos motivos: en
algunos sistemas los archivos sólo pueden ser abiertos de a un programa por la vez; en otros, lo que se haya escrito no se guardará realmente hasta no cerrar el archivo; o el límite de cantidad
de archivos que puede manejar un programa puede ser bajo, etc.

Para cerrar un archivo simplemente se debe llamar a:

In [ ]:
archivo.close()

### 11.2. Ejemplo de procesamiento de archivos

Por ejemplo, para mostrar todas las líneas de un archivo, precedidas por el número de línea,
podemos hacerlo como en el Código 11.1.

In [ ]:
archivo = open("archivo.txt")
i = 1
for linea in archivo:
    linea = linea.rstrip("\n")
    print("%4d: %s" & (i,linea))
    i+=1
archivo.close()

La llamada a rstrip es necesaria ya que cada línea que se lee del archivo contiene un fin
de línea y con la llamada a rstrip("\n") se remueve.

Otra opción para hacer exactamente lo mismo sería utilizar la función de Python
enumerate(secuencia). Esta función devuelve un contador por cada uno de los elementos
que se recorren, puede usarse con cualquier tipo de secuencia, incluyendo archivos. La versión
equivalente se muestra en el Código 11.2.

In [ ]:
archivo = open("archivo.txt")
for i, linea in enumerate(archivo):
    linea = linea.rstrip("\n")
    print " %4d: %s" % (i, linea)
archivo.close()

### 11.3. Modo de apertura de los archivos

La función open recibe un parámetro opcional para indicar el modo en que se abrirá el
archivo. Los tres modos de apertura que se pueden especificar son:

Modo de sólo lectura (’r’). En este caso no es posible realizar modificaciones sobre el
archivo, solamente leer su contenido.

Modo de sólo escritura (’w’). En este caso el archivo es truncado (vaciado) si existe, y se
lo crea si no existe.

Modo sólo escritura posicionándose al final del archivo (’a’). En este caso se crea el archivo,
si no existe, pero en caso de que exista se posiciona al final, manteniendo el contenido
original.

Por otro lado, en cualquiera de estos modos se puede agregar un + para pasar a un modo
lectura-escritura. El comportamiento de r+ y de w+ no es el mismo, ya que en el primer caso se
tiene el archivo completo, y en el segundo caso se trunca el archivo, perdiendo así los datos.

En caso de que no se especifique el modo, los archivos serán abiertos en modo sólo lectura
(r).

### 11.4. Escribir en un archivo

De la misma forma que para la lectura, existen dos formas distintas de escribir a un archivo.
Mediante cadenas:

In [ ]:
archivo.write(cadena)

O mediante listas de cadenas:

In [ ]:
archivo.writelines(lista_de_cadenas)

Así como la función read devuelve las líneas con los caracteres de fin de línea (\n), será
necesario agregar los caracteres de fin de línea a las cadenas que se vayan a escribir en el
archivo.

In [ ]:
saludo = open("saludo.py", "w")
saludo.write("""
print "Hola Mundo"
""")
saludo.close()

### 11.5. Agregar información a un archivo

Abrir un archivo en modo agregar al final puede parece raro, pero es bastante útil.

Uno de sus usos es para escribir un archivo de bitácora (o archivo de log), que nos permita
ver los distintos eventos que se fueron sucediendo, y así encontrar la secuencia de pasos (no
siempre evidente) que hace nuestro programa.

Esta es una forma muy habitual de buscar problemas o hacer un seguimiento de los sucesos.
Para los administradores de sistemas es una herramienta esencial de trabajo.

En el Código 11.4 se muestra un módulo para manejo de logs, que se encarga de la apertura
del archivo, del guardado de las líneas una por una y del cerrado final del archivo.

En este módulo se utiliza el módulo de Python datetime para obtener la fecha y hora
actual que se guardará en los archivos. Es importante notar que en el módulo mostrado no se
abre o cierra un archivo en particular, sino que las funciones están programadas de modo tal
que puedan ser utilizadas desde otro programa.

Se trata de un módulo genérico que podrá ser utilizado por diversos programas, que requieran
la funcionalidad de registrar los posibles errores o eventos que se produzcan durante
la ejecución.

Para utilizar este módulo, será necesario primero llamar a abrir_log para abrir el archivo
de log, luego llamar a guardar_log por cada mensaje que se quiera registrar, y finalmente
llamar a cerrar_log cuando se quiera concluir la registración de mensajes.

Por ejemplo, en el Código 11.5 se muestra un posible programa que utiliza el módulo de
log incluido anteriormente.

In [2]:
# El módulo datetime se utiliza para obtener la fecha y hora actual.
import datetime

def abrir_log(nombre_log):
    """ Abre el archivo de log indicado. Devuelve el archivo abierto.
    Pre: el nombre corresponde a un nombre de archivo válido.
    Post: el archivo ha sido abierto posicionándose al final. """
    
    archivo_log = open(nombre_log, "a")
    guardar_log(archivo_log, "Iniciando registro de errores")
    return archivo_log

def guardar_log(archivo_log, mensaje):
    """ Guarda el mensaje en el archivo de log, con la hora actual.
    Pre: el archivo de log ha sido abierto correctamente.
    Post: el mensaje ha sido escrito al final del archivo. """
    #Obtiene la hora actual en formato de texto
    hora_actual = str(datetime.datetime.now())
    #Guarda la hora actual y el mensaje de error en el archivo
    archivo_log.write(hora_actual+" "+mensaje+"\n")
    
def cerrar_log(archivo_log):
    """ Cierra el archivo de log.
    Pre: el archivo de log ha sido abierto correctamente.
    Post: el archivo de log se ha cerrado. """
    guardar_log(archivo_log, "Fin del registro de errores")
    archivo_log.close()

In [ ]:
import log
#Constante que contiene el nombre del archivo de log a utilizar
ARCHIVO_LOG = "mi_log.txt"

def main():
    # Al comenzar, abrir el log
    archivo_log = log.abrir_log(ARCHIVO_LOG)
    # ...
    # Hacer cosas que pueden dar error
    if error:
        guardar_log(archivo_log, "ERROR: "+error)
    #...
    #Finalmente cerrar el archivo
    log.cerrar_log(archivo_log)

main()

Este código, que incluye el módulo log mostrado anteriormente, muestra una forma básica
de utilizar un archivo de log. Al iniciarse el programa se abre el archivo de log, de forma
que queda registrada la fecha y hora de inicio. Posteriormente se realizan tareas varias que
podrían provocar errores, y de haber algún error se lo guarda en el archivo de log. Finalmente,
al terminar el programa, se cierra el archivo de log, quedando registrada la fecha y hora de
finalización.

El archivo de log generado tendrá la forma:

2010-04-10 15:20:32.229556 Iniciando registro de errores
2010-04-10 15:20:50.721415 ERROR: no se pudo acceder al recurso
2010-04-10 15:21:58.625432 ERROR: formato de entrada inválido
2010-04-10 15:22:10.109376 Fin del registro de errores

### 11.6 Manipular un archivo en forma binaria

No todos los archivos son archivos de texto, y por lo tanto no todos los archivos pueden ser
procesados por líneas. Existen archivos en los que cada byte tiene un significado particular, y
es necesario manipularlos conociendo el formato en que están los datos para poder procesar
esa información.

Para abrir un archivo y manejarlo de forma binaria es necesario agregarle una ’b’ al parametro
de modo.

Para procesar el archivo de a bytes en lugar de líneas, se utiliza la función
contenido = archivo.read(n) para leer n bytes y archivo.write(contenido), para
escribir contenido en la posición actual del archivo.

Al manejar un archivo binario, es necesario poder conocer la posición actual en el archivo
y poder modificarla. Para obtener la posición actual se utiliza archivo.tell(), que indica la
cantidad de bytes desde el comienzo del archivo.

Para modificar la posición actual se utiliza archivo.seek(corrimiento, desde), que
permite desplazarse una cantidad de bytes en el archivo, contando desde el comienzo del archivo,
desde la posición actual o desde el final.

### Unidad 12: Manejo de errores y excepciones

### 12.1. Errores

En un programa podemos encontrarnos con distintos tipos de errores pero a grandes rasgos
podemos decir que todos los errores pertenecen a una de las siguientes categorías.

Errores de sintaxis: estos errores son seguramente los más simples de resolver, pues son
detectados por el intérprete (o por el compilador, según el tipo de lenguaje que estemos
utilizando) al procesar el código fuente y generalmente son consecuencia de equivocaciones
al escribir el programa. En el caso de Python estos errores son indicados con un
mensaje SyntaxError. Por ejemplo, si trabajando con Python intentamos definir una función
y en lugar de def escribimos dev.

Errores semánticos: se dan cuando un programa, a pesar de no generar mensajes de error,
no produce el resultado esperado. Esto puede deberse, por ejemplo, a un algoritmo incorrecto
o a la omisión de una sentencia.

Errores de ejecución: estos errores aparecen durante la ejecución del programa y su origen
puede ser diverso. En ocasiones pueden producirse por un uso incorrecto del programa
por parte del usuario, por ejemplo si el usuario ingresa una cadena cuando se espera
un número. En otras ocasiones pueden deberse a errores de programación, por ejemplo
si una función intenta acceder a la quinta posición de una lista de 3 elementos o realizar
una división por cero. Una causa común de errores de ejecución que generalmente excede
al programador y al usuario, son los recursos externos al programa, por ejemplo si el
programa intenta leer un archivo y el mismo se encuentra dañado.

Tanto a los errores de sintaxis como a los semánticos se los puede detectar y corregir durante
la construcción del programa ayudados por el intérprete y la ejecución de pruebas. Pero no
ocurre esto con los errores de ejecución ya que no siempre es posible saber cuando ocurrirán y
puede resultar muy complejo (o incluso casi imposible) reproducirlos. Es por ello que el resto
de la unidad nos centraremos en cómo preparar nuestros programas para lidiar con este tipo
de errores.

### 12.2. Excepciones

Los errores de ejecución son llamados comúnmente excepciones y por eso de ahora en más
utilizaremos ese nombre. Durante la ejecución de un programa, si dentro de una función surge una excepción y la función no la maneja, la excepción se propaga hacia la función que la invocó,
si esta otra tampoco la maneja, la excepción continua propagándose hasta llegar a la función
inicial del programa y si esta tampoco la maneja se interrumpe la ejecución del programa.
Veamos entonces como manejar excepciones.

### 12.2.1. Manejo de excepciones

Para el manejo de excepciones los lenguajes proveen ciertas palabras reservadas, que nos
permiten manejar las excepciones que puedan surgir y tomar acciones de recuperación para
evitar la interrupción del programa o, al menos, para realizar algunas acciones adicionales
antes de interrumpir el programa.

En el caso de Python, el manejo de excepciones se hace mediante los bloques que utilizan
las sentencias try, except y finally.

Dentro del bloque try se ubica todo el código que pueda llegar a levantar una excepción,
se utiliza el término levantar para referirse a la acción de generar una excepción.

A continuación se ubica el bloque except, que se encarga de capturar la excepción y nos
da la oportunidad de procesarla mostrando por ejemplo un mensaje adecuado al usuario.

Veamos qué sucede si se quiere realizar una división por cero:

In [4]:
dividendo = 5
divisor = 0
dividendo/divisor

ZeroDivisionError: division by zero

En este caso, se levantó la excepción ZeroDivisionError cuando se quiso hacer la división.
Para evitar que se levante la excepción y se detenga la ejecución del programa, se utiliza
el bloque try-except.

In [12]:
def dividir():
    dividendo = 5
    divisor = 0
    try:
        cociente = dividendo / divisor
    except: 
        print("No se permite la división por cero")
dividir()

No se permite la división por cero


Dado que dentro de un mismo bloque try pueden producirse excepciones de distinto tipo,
es posible utilizar varios bloques except, cada uno para capturar un tipo distinto de excepción.

Esto se hace especificando a continuación de la sentencia except el nombre de la excepción
que se pretende capturar. Un mismo bloque except puede atrapar varios tipos de excepciones,
lo cual se hace especificando los nombres de la excepciones separados por comas a continuación
de la palabra except. Es importante destacar que si bien luego de un bloque try puede
haber varios bloques except, se ejecutará, a lo sumo, uno de ellos.

In [ ]:
try:
    # aquí ponemos el código que puede lanzar excepciones
except IOError:
    # entrará aquí en caso que se haya producido
    # una excepción IOError
except ZeroDivisionError:
    # entrará aquí en caso que se haya producido
    # una excepción ZeroDivisionError
except:
    # entrará aquí en caso que se haya producido
    # una excepción que no corresponda a ninguno
    # de los tipos especificados en los except previos

Como se muestra en el ejemplo precedente también es posible utilizar una sentencia
except sin especificar el tipo de excepción a capturar, en cuyo caso se captura cualquier excepción,
sin importar su tipo. Cabe destacar, también, que en caso de utilizar una sentencia
except sin especificar el tipo, la misma debe ser siempre la última de las sentencias except,
es decir que el siguiente fragmento de código es incorrecto.

In [ ]:
try:
    # aquí ponemos el código que puede lanzar excepciones
except:
    # ERROR de sintaxis, esta sentencia no puede estar aquí,
    # sino que debería estar luego del except IOError.
except IOError:
    # Manejo de la excepción de entrada/salida

Finalmente, puede ubicarse un bloque finally donde se escriben las sentencias de finalización,
que son típicamente acciones de limpieza. La particularidad del bloque finally es que
se ejecuta siempre, haya surgido una excepción o no. Si hay un bloque except, no es necesario
que esté presente el finally, y es posible tener un bloque try sólo con finally, sin except.

Veamos ahora como es que actúa Python al encontrarse con estos bloques. Python comienza
a ejecutar las instrucciones que se encuentran dentro de un bloque try normalmente. Si
durante la ejecución de esas instrucciones se levanta una excepción, Python interrumpe la ejecución
en el punto exacto en que surgió la excepción y pasa a la ejecución del bloque except
correspondiente.

Para ello, Python verifica uno a uno los bloques except y si encuentra alguno cuyo tipo
haga referencia al tipo de excepción levantada, comienza a ejecutarlo. Sino encuentra ningún
bloque del tipo correspondiente pero hay un bloque except sin tipo, lo ejecuta. Al terminar de
ejecutar el bloque correspondiente, se pasa a la ejecución del bloque finally, si se encuentra
definido.

Si, por otra parte, no hay problemas durante la ejecución del bloque try, se completa la
ejecución del bloque, y luego se pasa directamente a la ejecución del bloque finally (si es
que está definido).

Bajemos todo esto a un ejemplo concreto, supongamos que nuestro programa tiene que procesar
cierta información ingresada por el usuario y guardarla en un archivo. Dado que el acceso
a archivos puede levantar excepciones, siempre deberíamos colocar el código de manipulación
de archivos dentro de un bloque try. Luego deberíamos colocar un bloque except que atrape
una excepción del tipo IOError, que es el tipo de excepciones que lanzan la funciones de manipulación
de archivos. Adicionalmente podríamos agregar un bloque except sin tipo por si
surge alguna otra excepción. Finalmente deberíamos agregar un bloque finally para cerrar
el archivo, haya surgido o no una excepción.

In [ ]:
try:
    archivo = open("miarchivo.txt")
    # procesar el archivo
    except IOError:
        print "Error de entrada/salida."
        # realizar procesamiento adicional
    except:
        # procesar la excepción
    
    finally:
        # si el archivo no está cerrado hay que cerrarlo
        if not(archivo.closed):
        archivo.close()

### 12.2.2. Procesamiento y propagación de excepciones

Hemos visto cómo atrapar excepciones, es necesario ahora que veamos qué se supone que
hagamos al atrapar una excepción. En primer lugar podríamos ejecutar alguna lógica particular
del caso como: cerrar un archivo, realizar una procesamiento alternativo al del bloque try, etc.
Pero más allá de esto tenemos algunas opciones genéricas que consisten en: dejar constancia
de la ocurrencia de la excepción, propagar la excepción o, incluso, hacer ambas cosas.

Para dejar constancia de la ocurrencia de la excepción, se puede escribir en un archivo de
log o simplemente mostrar un mensaje en pantalla. Generalmente cuando se deja constancia de
la ocurrencia de una excepción se suele brindar alguna información del contexto en que ocurrió
la excepción, por ejemplo: tipo de excepción ocurrida, momento en que ocurrió la excepción y
cuáles fueron las llamadas previas a la excepción. El objetivo de esta información es facilitar el
diagnóstico en caso de que alguien deba corregir el programa para evitar que la excepción siga
apareciendo.

Es posible, por otra parte, que luego de realizar algún procesamiento particular del caso se
quiera que la excepción se propague hacia la función que había invocado a la función actual.
Para hacer esto Python nos brinda la instrucción raise.

Si se invoca esta instrucción dentro de un bloque except, sin pasarle parámetros, Python
levantará la excepción atrapada por ese bloque.

También podría ocurrir que en lugar de propagar la excepción tal cual fue atrapada, quisiéramos
lanzar una excepción distinta, más significativa para quien invocó a la función actual
y que posiblemente contenga cierta información de contexto. Para levantar una excepción de
cualquier tipo, utilizamos también la sentencia raise, pero indicándole el tipo de excepción
que deseamos lanzar y pasando a la excepción los parámetros con información adicional que
queramos brindar.

El siguiente fragmento de código muestra este uso de raise.

In [3]:
def dividir(dividendo, divisor):
    try:
        resultado = dividendo / divisor
        return resultado
    except ZeroDivisionError:
        raise ZeroDivisionError("El divisor no puede ser cero")
        
dividir(20,0)

ZeroDivisionError: El divisor no puede ser cero

### 12.2.3. Acceso a información de contexto

Para acceder a la información de contexto estando dentro de un bloque except existen dos
alternativas. Se puede utilizar la función exc_info del módulo sys. Esta función devuelve
una tupla con información sobre la última excepción atrapada en un bloque except. Dicha
tupla contiene tres elementos: el tipo de excepción, el valor de la excepción y las llamadas
realizadas.

Otra forma de obtener información sobre la excepción es utilizando la misma sentencia
except, pasándole un identificador para que almacene una referencia a la excepción atrapada.

In [ ]:
try:
    # código que puede lanzar una excepción
except Exception, ex:
    # procesamiento de la excepción cuya información
    # es accesible a través del identificador ex

### 12.3. Validaciones

Las validaciones son técnicas que permiten asegurar que los valores con los que se vaya a
operar estén dentro de determinado dominio.

Estas técnicas son particularmente importantes al momento de utilizar entradas del usuario
o de un archivo (o entradas externas en general) en nuestro código, y también se las utiliza para
comprobar precondiciones. Al uso intensivo de estas técnicas se lo suele llamar programación
defensiva.

Si bien quien invoca una función debe preocuparse de cumplir con las precondiciones de
ésta, si las validaciones están hechas correctamente pueden devolver información valiosa para
que el invocante pueda actuar en consecuencia.

Hay distintas formas de comprobar el dominio de un dato. Se puede comprobar el contenido;
que una variable sea de un tipo en particular; o que el dato tenga determinada característica,
como que deba ser “comparable”, o “iterable”.

También se debe tener en cuenta qué hará nuestro código cuando una validación falle, ya
que queremos darle información al invocante que le sirva para procesar el error. El error producido
tiene que ser fácilmente reconocible. En algunos casos, como por ejemplo cuando se quiere
devolver una posición, devolver -1 nos puede asegurar que el invocante lo vaya a reconocer.
En otros casos, levantar una excepción es una solución más elegante.

En cualquier caso, lo importante es que el resultado generado por nuestro código cuando
funciona correctamente y el resultado generado cuando falla debe ser claramente distinto. Por
ejemplo, si el código debe devolver un elemento de una secuencia, no es una buena idea que
devuelva None en el caso de que la secuencia esté vacía, ya que None es un elemento válido
dentro de una secuencia.

### 12.3.1. Comprobaciones por contenido

Cuando queremos validar que los datos provistos a una porción de código contengan la
información apropiada, ya sea porque esa información la ingresó un usuario, fue leída de un
archivo, o porque por cualquier motivo es posible que sea incorrecta, es deseable comprobar
que el contenido de las variables a utilizar estén dentro de los valores con los que se puede
operar.

Estas comprobaciones no siempre son posibles, ya que en ciertas situaciones puede ser muy
costoso corroborar las precondiciones de una función. Es por ello que este tipo de comprobaciones
se realizan sólo cuando sea posible.

Por ejemplo, la función factorial está definida para los números naturales incluyendo el 0.
Es posible utilizar assert (que es otra forma de levantar una excepción) para comprobar las
precondiciones de factorial.

In [8]:
def factorial(n):
    """Calcula el factorial de n.
    Pre: n debe ser un entero, mayor igual a 0
    Post: se devuelve el valor del factorial pedido"""
    
    assert n >=0, "n debe ser mayor igual a 0"
    fact=1
    for i in range(2, n+1):
        fact*=i
    return fact
factorial(-22)

AssertionError: n debe ser mayor igual a 0

### 12.3.2. Entrada del usuario

En el caso particular de una porción de código que trate con entrada del usuario, no se
debe asumir que el usuario vaya a ingresar los datos correctamente, ya que los seres humanos
tienden a cometer errores al ingresar información.

Por ejemplo, si se desea que un usuario ingrese un número, no se debe asumir que vaya a
ingresarlo correctamente. Se lo debe guardar en una cadena y luego convertir a un número, es
por eso que es recomendable el uso de la función raw_input ya que devuelve una cadena que
puede ser procesada posteriormente.

In [10]:
def lee_entero():
    """Solicita un valor entero y lo devuelve.
       Si el valor ingresado no es entero, lanza una excepción. """
    valor = input("Ingrese un número entero: ")
    return int(valor)
lee_entero()

Ingrese un número entero: a


ValueError: invalid literal for int() with base 10: 'a'

Esta función devuelve un valor entero, o lanza una excepción si la conversión no fue posible.
Sin embargo, esto no es suficiente. En el caso en el que el usuario no haya ingresado la
información correctamente, es necesario volver a solicitarla.

In [30]:
def lee_entero():
    """Solicita un valor entero y lo devuelve.
       Si el valor ingresado no es entero, lanza una excepción. """
    while True:
        valor = input("Ingrese un número entero: ")
        try:
            valor = int(valor)
            return int(valor)
        except ValueError:
            print("ATENCIÓN: Debe ingresar un número entero.")
            
lee_entero()

Ingrese un número entero: a
ATENCIÓN: Debe ingresar un número entero.
Ingrese un número entero: a
ATENCIÓN: Debe ingresar un número entero.
Ingrese un número entero: a
ATENCIÓN: Debe ingresar un número entero.
Ingrese un número entero: a
ATENCIÓN: Debe ingresar un número entero.
Ingrese un número entero: a
ATENCIÓN: Debe ingresar un número entero.
Ingrese un número entero: a
ATENCIÓN: Debe ingresar un número entero.
Ingrese un número entero: 3


3

Podría ser deseable, además, poner un límite a la cantidad máxima de intentos que el usuario
tiene para ingresar la información correctamente y, superada esa cantidad máxima de intentos,
levantar una excepción para que sea manejada por el código invocante.

In [5]:
def lee_entero():
    """ Solicita un valor entero y lo devuelve.
        Si el valor ingresado no es entero, da 5 intentos para ingresarlo
        correctamente, y de no ser así, lanza una excepción. """
    intentos = 0
    while intentos < 5:
        valor = input("Ingrese un número entero: ")
        try:
            valor = int(valor)
            return int(valor)
        except ValueError:
            intentos +=1
    raise ValueError("Valor incorrecto ingresado en 5 intentos")
            
lee_entero()

Ingrese un número entero: A
Ingrese un número entero: a
Ingrese un número entero: a
Ingrese un número entero: a
Ingrese un número entero: a


ValueError: Valor incorrecto ingresado en 5 intentos

Por otro lado, cuando la entrada ingresada sea una cadena, no es esperable que el usuario
la vaya a ingresar en mayúsculas o minúsculas, ambos casos deben ser considerados.

In [4]:
def lee_opcion():
    """ Solicita una opción de menú y la devuelve. """
    while True:
        print("Ingrese A (Altas), - B (Bajas) - M(Modificaciones): "),
        opcion = input().upper()
        if opcion in ["A", "B", "M"]:
            return opcion
lee_opcion()

Ingrese A (Altas), - B (Bajas) - M(Modificaciones): 
BB
Ingrese A (Altas), - B (Bajas) - M(Modificaciones): 
B


'B'

### 12.3.3. Comprobaciones por tipo

En esta clase de comprobaciones nos interesa el tipo del dato que vamos a tratar de validar,
Python nos indica el tipo de una variable usando la función type(variable). Por ejemplo,
para comprobar que una variable contenga un tipo entero podemos hacer:

In [ ]:
if type(i) != int:
    raise TypeError "i debe ser del tipo int"

Sin embargo, ya hemos visto que tanto las listas como las tuplas y las cadenas son secuencias,
y muchas de las funciones utilizadas puede utilizar cualquiera de estas secuencias. De la
misma manera, una función puede utilizar un valor numérico, y que opere correctamente ya
sea entero, flotante, o complejo.

Es posible comprobar el tipo de nuestra variable contra una secuencia de tipos posibles.

In [ ]:
if type(i) not in (int, float, long, complex):
    raise TypeError "i debe ser numérico"

Si bien esto es bastante más flexible que el ejemplo anterior, también puede ser restrictivo ya
que -como se verá más adelante- cada programador puede definir sus propios tipos utilizando
como base los que ya están definidos. Con este código se están descartando todos los tipos que
se basen en int, float, long o complex.

Para poder incluir estos tipos en la comprobación a realizar, Python nos provee de la función
isinstance(variable, tipos).

In [ ]:
if not isinstance(i, (int, float, long, complex) ):
    raise TypeError "i debe ser numérico"

Con esto comprobamos si una variable es de determinado tipo o subtipo de éste. Esta opción
es bastante flexible, pero existen aún más opciones.

Para la mayoría de los tipos básicos de Python existe una función que se llama de la misma
manera que el tipo que devuelve un elemento de ese tipo, por ejemplo, int() devuelve 0,
dict() devuelve {} y así. Además, estas funciones suelen poder recibir un elemento de otro
tipo para tratar de convertirlo, por ejemplo, int(3.0) devuelve 3, list("Hola") devuelve
[’H’, ’o’, ’l’, ’a’].

Usando está conversión conseguimos dos cosas: podemos convertir un tipo recibido al que
realmente necesitamos, a la vez que tenemos una copia de este, dejando el original intacto, que
es importante cuando estamos tratando con tipos mutables.

Por ejemplo, si se quiere contar con una función de división entera que pueda recibir diversos
parámetros, podría hacerse de la siguiente manera.

In [19]:
def division_entera(x,y):
    """Calcula la división entera después de convertir los parámetros a
    enteros."""
    try:
        dividendo = int(x)
        divisor = int(y)
        return (dividendo/divisor)
    except ValueError:
        raise ValueError("x e y deben poder convertirse a enteros")
    except ZeroDivisionError:
        raise ValueError("y no puede ser cero")
division_entera(20,0)

ValueError: y no puede ser cero

### 12.3.4. Comprobaciones por características

Otra posible comprobación, dejando de lado los tipos, consiste en verificar si una variable
tiene determinada característica o no. Python promueve este tipo de programación, ya que el
mismo intérprete utiliza este tipo de comprobaciones. Por ejemplo, para imprimir una variable,
Python convierte esa variable a una cadena, no hay en el interprete una verificación para cada
tipo, sino que busca una función especial, llamada __str__, en la variable a imprimir, y si
existe, la utiliza para convertir la variable a una cadena.

Para comprobar si una variable tiene o no una función Python provee la función
hasattr(variable, atributo), donde atributo puede ser el nombre de la función o
de la variable que se quiera verificar. Se verá más sobre atributos en la unidad de Programación
Orientada a Objetos.

Por ejemplo, existe la función __add__ para realizar operaciones de suma entre elementos.
Si se quiere corroborar si un elemento es sumable, se lo haría de la siguiente forma.

In [ ]:
if not hasattr(i,"__add__"):
    raise TypeError("El elemento no es sumable")

Sin embargo, que el atributo exista no quiere decir que vaya a funcionar correctamente en
todos los casos. Por ejemplo, tanto las cadenas como los números definen su propia “suma”,
pero no es posible sumar cadenas y números, de modo que en este caso sería necesario tener
en cuenta una posible excepción.

Por otro lado, en la mayoría de los casos se puede aplicar la frase: es más fácil pedir perdón que
permiso, atribuída a la programadora Grace Hopper. Es decir, en este caso es más sencillo hacer
la suma dentro de un bloque try y manejar la excepción en caso de error, que saber cuáles son
los detalles de la implementación de __add__ de cada tipo interactuante.

### 14. Objetos

Los objetos son una manera de organizar datos y de relacionar esos datos con el código
apropiado para manejarlo. Son los protagonistas de un paradigma de programación llamado
Programación Orientada a Objetos.

Nosotros ya usamos objetos en Python sin mencionarlo explícitamente. Es más, todos los
tipos de datos que Python nos provee son, en realidad, objetos.

De forma que, cuando utilizamos miarchivo.readline(), le estamos diciendo a Python
que llame a la función readline del tipo file para miarchivo que es lo mismo que decir
que llame al método readline del objeto miarchivo.

A su vez, a las variables que un objeto contiene, se las llama atributos.

### 14.1. Tipos

En los temas que vimos hasta ahora nos hemos encontrado con numerosos tipos provistos
por Python, los números, las cadenas de caracteres, las listas, las tuplas, los diccionarios, los archivos,
etc. Cada uno de estos tipos tiene sus características, tienen operaciones propias de cada
uno y nos proveen una gran cantidad de funcionalidades que podemos utilizar para nuestros
programas.

Como ya se dijo en unidades anteriores, para saber de qué tipo es una variable, utilizamos
la función type, y para saber qué métodos y atributos tiene esa variable utilizamos la función
dir.

In [ ]:
>>> a = open("archivo.txt")
>>> type(a)
<type ’file’>
>>> dir(a)
[’__class__’, ’__delattr__’, ’__doc__’, ’__enter__’, ’__exit__’,
’__getattribute__’, ’__hash__’, ’__init__’, ’__iter__’, ’__new__’,
’__reduce__’, ’__reduce_ex__’, ’__repr__’, ’__setattr__’, ’__str__’,
’close’, ’closed’, ’encoding’, ’fileno’, ’flush’, ’isatty’, ’mode’, ’name’,
’newlines’, ’next’, ’read’, ’readinto’, ’readline’, ’readlines’, ’seek’,
’softspace’, ’tell’, ’truncate’, ’write’, ’writelines’, ’xreadlines’]

En este caso, la función dir nos muestra los métodos que tiene un objeto del tipo file.
Podemos ver en el listado los métodos que ya hemos visto al operar con archivos, junto con
otros métodos con nombres raros como __str__, o __doc__, estos métodos son especiales en
Python, más adelante veremos para qué sirven y cómo se usan.

En el listado que nos da dir están los atributos y métodos mezclados. Si necesitamos saber
cuáles son atributos y cuáles son métodos, podemos hacerlo nuevamente mediante el uso de
type.

In [ ]:
>>> type (a.name)
<type ’str’>
>>> a.name
’archivo.txt’
>>> type (a.tell)
<type ’builtin_function_or_method’>
>>> a.tell()
0LEs importante notar que cuando decimos objetos podemos estar haciendo referencia a dos
cosas parecidas, pero distintas.

Es decir que name es un atributo del objeto (el nombre del archivo), mientras que tell es
un método, que para utilizarlo debemos llamarlo con paréntesis.

### 14.2. Qué es un objeto

En Python, todos los tipos son objetos. Pero no en todos los lenguajes de programación es
así. En general, podemos decir que un objeto es una forma ordenada de agrupar datos (los
atributos) y operaciones a utilizar sobre esos datos (los métodos).

Es importante notar que cuando decimos objetos podemos estar haciendo referencia a dos
cosas parecidas, pero distintas.

Por un lado, la definición del tipo, donde se indican cuáles son los atributos y métodos que
van a tener todas las variables que sean de ese tipo. Esta definición se llama específicamente, la
clase del objeto.

A partir de una clase es posible crear distintas variables que son de ese tipo. A las variables
que son de una clase en particular, se las llama instancia de esa clase.

### 14.3. Definiendo nuevos tipos

Sin bien Python nos provee con un gran número de tipos ya definidos, en muchas situaciones
utilizar solamente los tipos provistos por el lenguaje resultará insuficiente. En estas situaciones
queremos poder crear nuestros propios tipos, que almacenen la información relevante
para el problema a resolver y contengan las funciones para operar con esa información.

Por ejemplo, si se quiere representar un punto en el plano, es posible hacerlo mediante una
tupla de dos elementos, pero esta implementación es limitada, ya que si se quiere poder operar
con distintos puntos (sumarlos, restarlos o calcular la distancia entre ellos) se deberán tener
funciones sueltas para realizar las diversas operaciones.

Podemos hacer algo mejor definiendo un nuevo tipo Punto, que almacene la información
relacionada con el punto, y contenga las operaciones nos interese realizar sobre él.

### 14.3.1. Nuestra primera clase: Punto

Queremos definir nuestra clase que represente un punto en el plano. Lo primero que debemos
notar es que existen varias formas de representar un punto en el plano, por ejemplo, coordenadas
polares o coordenadas cartesianas. Además, existen varias operaciones que se pueden
realizar sobre un punto del plano, e implementarlas todas podría llevar mucho tiempo.

En esta primera implementación, optaremos por utilizar la representación de coordenadas
cartesianas, e iremos implementando las operaciones a medida que las vayamos necesitando.

En primer lugar, creamos una clase Punto que simplemente almacena las coordenadas.

In [4]:
class Punto(object):
    """Representación de un punto en el plano, los atributos x e y 
       que representan los valores de las coordenadas cartesianas."""
    def __init__(self, x=0, y=0):
        "Constructor de Punto, x e y deben ser numéricos"
        self.x = x
        self.y = y

En la primera línea de código indicamos que vamos a crear una nueva clase, llamada Punto
La palabra object entre paréntesis indica que la clase que estamos creando es un objeto básico,
no está basado en ningún objeto más complejo.

Además definimos uno de los métodos especiales, __init__, el constructor de la clase.
Este método se llama cada vez que se crea una nueva instancia de la clase.

Este método, al igual que todos los métodos de cualquier clase, recibe como primer parámetro
a la instancia sobre la que está trabajando. Por convención a ese primer parámetro se lo suele llamar self (que podríamos traducir como yo mismo), pero puede llamarse de cualquier
forma.

Para definir atributos, basta con definir una variable dentro de la instancia, es una buena
idea definir todos los atributos de nuestras instancias en el constructor, de modo que se creen
con algún valor válido. En nuestro ejemplo self.x y self.y y se usarán como punto.x y
punto.y.

Para utilizar esta clase que acabamos de definir, lo haremos de la siguiente forma:

In [9]:
p=Punto(5,7)
print(p)
print(p.x)
print(p.y)

5
7


Al realizar la llamada Punto(5,7), se creó un nuevo punto, y se almacenó una referencia
a ese punto en la variable p. 5 y 7 son los valores que se asignaron a x e y respectivamente.

Si bien nosotros no lo invocamos explícitamente, internamente Python realizó la llamada al
método __init__, asignando así los valores de la forma que se indica en el constructor.

### 14.3.2 Agregando validaciones al constructor

Hemos creado una clase Punto que permite guardar valores x e y. Sin embargo, por más
que en la documentación se indique que los valores deben ser numéricos, el código mostrado
hasta ahora no impide que a x e y se les asigne un valor cualquiera, no numérico.

In [10]:
q=Punto("A", True)
print(q.x)
print(q.y)

A
True


Si queremos impedir que esto suceda, debemos agregar validaciones al constructor, como
las vistas en unidades anteriores.

Verificaremos que los valores pasados para x e y sean numéricos, utilizando la función
es_numero, que incluiremos en un módulo llamado validaciones:

In [15]:
def es_numero(valor):
    """ Indica si un valor es númerico o no. """
    return isinstance(valor, (int, float, complex))

class Punto(object):
    """Representación de un punto en el plano, los atributos x e y 
       que representan los valores de las coordenadas cartesianas."""
    def __init__(self, x=0, y=0):
        """ Constructor de Punto, x e y deben ser numéricos,
            de no ser así, se levanta una excepción TypeError """
        if es_numero(x) and es_numero(y):
            self.x = x
            self.y = y
        else:
            raise TypeError("x e y deben ser valores númericos")

Este constructor impide que se creen instancias con valores inválidos para x e y.

In [16]:
q=Punto("A", True)

TypeError: x e y deben ser valores númericos

### 14.3.3. Agregando operaciones

Hasta ahora hemos creado una clase Punto que permite construirla con un par de valores,
que deben ser sí o sí numéricos, pero no podemos operar con esos valores. Para apreciar la
potencia de los objetos, tenemos que definir operaciones adicionales que vayamos a querer
realizar sobre esos puntos.

Queremos, por ejemplo, poder calcular la distancia entre dos puntos. Para ello definimos
un nuevo método distancia que recibe el punto de la instancia actual y el punto para el cual
se quiere calcular la distancia.

In [27]:
class Punto(object):
    """Representación de un punto en el plano, los atributos x e y 
       que representan los valores de las coordenadas cartesianas."""
    def __init__(self, x=0, y=0):
        """ Constructor de Punto, x e y deben ser numéricos,
            de no ser así, se levanta una excepción TypeError """
        if es_numero(x) and es_numero(y):
            self.x = x
            self.y = y
        else:
            raise TypeError("x e y deben ser valores númericos")
    def distancia(self, otro):
        """ Devuelve una distancia entre ambos puntos. """
        dx = self.x - otro.x
        dy = self.y - otro.y
        return(dx*dx + dy*dy)**0.5
    
def es_numero(valor):
    """ Indica si un valor es númerico o no. """
    return isinstance(valor, (int, float, complex))

In [28]:
p=Punto(5,7)
q=Punto(2,3)
print(p.distancia(q))

5.0


Podemos ver, sin embargo, que la operación para calcular la distancia incluye la operación
de restar dos puntos y la de obtener la norma de un vector. Sería deseable incluir también estas
dos operaciones dentro de la clase Punto.

Agregaremos, entonces, el método para restar dos puntos:

In [21]:
def restar(self, otro):
    """ Devuelve un nuevo punto, con la resta entre dos puntos. """
    return Punto(self.x - otro.x, self.y - otro.y)

La resta entre dos puntos es un nuevo punto. Es por ello que este método devuelve un
nuevo punto, en lugar de modificar el punto actual.

A continuación, definimos el método para calcular la norma del vector que se forma uniendo
un punto con el origen.

In [23]:
def norma(self):
    """ Devuelve la norma del vector que va desde el origen
        hasta el punto. """
    return (self.x*self.x + self.y*self.y)**0.5

En base a estos dos métodos podemos ahora volver a escribir el método distancia para
que aproveche el código ambos:

In [24]:
def distancia(self, otro):
    """ Devuelve la distancia entre ambos puntos. """
    r = self.restar(otro)
    return r.norma()

En definitiva, hemos definido tres operaciones en la clase Punto, que nos sirve para calcular
restas, normas de vectores al origen, y distancias entre puntos.

In [32]:
class Punto(object):
    """Representación de un punto en el plano, los atributos x e y 
       que representan los valores de las coordenadas cartesianas."""
    def __init__(self, x=0, y=0):
        """ Constructor de Punto, x e y deben ser numéricos,
            de no ser así, se levanta una excepción TypeError """
        if es_numero(x) and es_numero(y):
            self.x = x
            self.y = y
        else:
            raise TypeError("x e y deben ser valores númericos")
    
    def restar(self, otro):
        """ Devuelve un nuevo punto, con la resta entre dos puntos. """
        return Punto(self.x - otro.x, self.y - otro.y)
    
    def norma(self):
        """ Devuelve la norma del vector que va desde el origen
            hasta el punto. """
        return (self.x*self.x + self.y*self.y)**0.5
    
    def distancia(self, otro):
        """ Devuelve la distancia entre ambos puntos. """
        r = self.restar(otro)
        return r.norma()
    
def es_numero(valor):
    """ Indica si un valor es númerico o no. """
    return isinstance(valor, (int, float, complex))

In [35]:
p=Punto(5,7)
q=Punto(2,3)
r= p.restar(q)
print(r.x,',', r.y)
print(r.norma())
q.distancia(r)

3 , 4
5.0


1.4142135623730951

### 14.4. Métodos especiales

Así como el constructor, __init__, existen diversos métodos especiales que, si están definidos
en nuestra clase, Python los llamará por nosotros cuando se utilice una instancia en
situaciones particulares.

### 14.4.1. Un método para mostrar objetos

Para mostrar objetos, Python indica que hay que agregarle a la clase un método especial,
llamado __str__ que debe devolver una cadena de caracteres con lo que queremos mostrar.
Ese método se invoca cada vez que se llama a la función str.

El método __str__ tiene un solo parámetro, self.

En nuestro caso decidimos mostrar el punto como un par ordenado, por lo que escribimos
el siguiente método dentro de la clase Punto:

In [36]:
class Punto(object):
    """Representación de un punto en el plano, los atributos x e y 
       que representan los valores de las coordenadas cartesianas."""
    def __init__(self, x=0, y=0):
        """ Constructor de Punto, x e y deben ser numéricos,
            de no ser así, se levanta una excepción TypeError """
        if es_numero(x) and es_numero(y):
            self.x = x
            self.y = y
        else:
            raise TypeError("x e y deben ser valores númericos")
    def __str__(self):
        """ Muestra el punto como un par ordenado. """
        return "(" + str(self.x) + ", " + str(self.y) + ")"
    
    def restar(self, otro):
        """ Devuelve un nuevo punto, con la resta entre dos puntos. """
        return Punto(self.x - otro.x, self.y - otro.y)
    
    def norma(self):
        """ Devuelve la norma del vector que va desde el origen
            hasta el punto. """
        return (self.x*self.x + self.y*self.y)**0.5
    
    def distancia(self, otro):
        """ Devuelve la distancia entre ambos puntos. """
        r = self.restar(otro)
        return r.norma()
    
def es_numero(valor):
    """ Indica si un valor es númerico o no. """
    return isinstance(valor, (int, float, complex))

Una vez definido este método, nuestro punto se mostrará como un par ordenado cuando
se necesite una representación de cadenas.

In [39]:
p=Punto(-6,18)

In [40]:
str(p)

'(-6, 18)'

In [41]:
print(p)

(-6, 18)


Vemos que con str(p) se obtiene la cadena construida dentro de __str__, y que internamente
Python llama a __str__ cuando se le pide que imprima una variable de la clase Punto.

### 14.4.2. Métodos para operar matemáticamente

Ya hemos visto un método que permitía restar dos puntos. Si bien esta implementación es
perfectamente válida, no es posible usar esa función para realizar una resta con el operador -.

In [42]:
p=Punto(3,4)
q=Punto(2,5)
print(p-q)

TypeError: unsupported operand type(s) for -: 'Punto' and 'Punto'

Si queremos que este operador (o el equivalente para la suma) funcione, será necesario
implementar algunos métodos especiales.

In [44]:
class Punto(object):
    """Representación de un punto en el plano, los atributos x e y 
       que representan los valores de las coordenadas cartesianas."""
    def __init__(self, x=0, y=0):
        """ Constructor de Punto, x e y deben ser numéricos,
            de no ser así, se levanta una excepción TypeError """
        if es_numero(x) and es_numero(y):
            self.x = x
            self.y = y
        else:
            raise TypeError("x e y deben ser valores númericos")
            
    def __str__(self):
        """ Muestra el punto como un par ordenado. """
        return "(" + str(self.x) + ", " + str(self.y) + ")"
    
    def __add__(self, otro):
        """ Devuelve la suma de ambos puntos. """
        return Punto(self.x + otro.x, self.y + otro.y)
    
    def __sub__(self,otro):
        """ Devuelve la resta de ambos puntos. """
        return Punto(self.x - otro.x, self.y - otro.y)
    
    def restar(self, otro):
        """ Devuelve un nuevo punto, con la resta entre dos puntos. """
        return Punto(self.x - otro.x, self.y - otro.y)
    
    def norma(self):
        """ Devuelve la norma del vector que va desde el origen
            hasta el punto. """
        return (self.x*self.x + self.y*self.y)**0.5
    
    def distancia(self, otro):
        """ Devuelve la distancia entre ambos puntos. """
        r = self.restar(otro)
        return r.norma()
    
def es_numero(valor):
    """ Indica si un valor es númerico o no. """
    return isinstance(valor, (int, float, complex))

El método __add__ es el que se utiliza para el operador +, el primer parámetro es el primer
operando de la suma, y el segundo parámetro el segundo operando. Debe devolver una
nueva instancia, nunca modificar la clase actual. De la misma forma, el método __sub__ es el
utilizado por el operador -.

Ahora es posible operar con los puntos directamente mediante los operadores, en lugar de
llamar a métodos:

In [45]:
p=Punto(3,4)
q=Punto(2,5)

In [46]:
print(p-q)

(1, -1)


In [47]:
print(p+q)

(5, 9)


De la misma forma, si se quiere poder utilizar cualquier otro operador matemático, será
necesario definir el método apropiado.

### 14.5. Creando clases más complejas

Nos contratan para diseñar una clase para evaluar la relación calidad-precio de diversos
hoteles. Nos dicen que los atributos que se cargarán de los hoteles son: nombre, ubicación,
puntaje obtenido por votación, y precio, y que además de guardar hoteles y mostrarlos, debemos
poder compararlos en términos de sus valores de relación calidad-precio, de modo tal que
x <y signifique que el hotel x es peor en cuanto a la relación calidad-precio que el hotel y, y que
dos hoteles son iguales si tienen la misma relación calidad-precio. La relación calidad-precio
de un hotel la definen nuestros clientes como (puntaje^2)*10./precio.

Además, y como resultado de todo esto, tendremos que ser capaces de ordenar de menor a
mayor una lista de hoteles, usando el orden que nos acaban de definir.

Averiguamos un poco más respecto de los atributos de los hoteles:

-El nombre y la ubicación deben ser cadenas no vacías.

-El puntaje debe ser un número (sin restricciones sobre su valor)

-El precio debe ser un número distinto de cero.

Empezamos a diseñar la clase

-El método __init__:

Creará objetos de la clase Hotel con los atributos que se indicaron (nombre, ubicación,
puntaje, precio).

Los valores por omisión para la construcción son: puntaje en 0, precio en
float("inf") (infinito), nombre y ubicación en ’*’ (el precio muy alto sirve para
que si no se informa el precio de un hotel, se asuma el mayor valor posible.

Necesitamos validar que puntaje y precio sean números (utilizaremos la función
es_numero que ya se usó en el caso de los puntos). Cuando un precio viene en
cero se reemplaza su valor por float("inf") (de modo de asegurar que el precio
nunca quede en cero).

Necesitamos validar que nombre y ubicación sean cadenas no vacías (para lo cual
tenemos que construir una función es_cadena_no_vacia).

Cuando los datos no satisfagan los requisitos se levantará una excepción
TypeError.

Contará con un método __str__ para mostrar a los hoteles mediante una cadena del
estilo:

"Hotel City de Mercedes - Puntaje: 3.25 - Precio: 78 pesos".

Respecto a la relación de orden entre hoteles, la clase deberá poder contar con los métodos
necesarios para realizar esas comparaciones y para ordenar una lista de hoteles.

Casi todas las tareas, podemos realizarlas con los temas vistos para la creación de la clase
Punto. Para el último ítem deberemos introducir nuevos métodos especiales.

__Ejercicio 14.1.__ Escribir la función es_cadena_no_vacia(valor) que decide si un valor
cualquiera es una cadena no vacía o no, e incluirla en el módulo validaciones.

In [10]:
def es_cadena_no_vacia(cadena):
    """ Valida si una cadena de texto se encuentra vacía o no. """
    if len(cadena) > 0:
        return cadena

El fragmento inicial de la clase programada en Python queda así:

In [2]:
class Hotel():
    """ Hotel: sus atributos son: nombre, ubicación, puntaje y precio. """
    
    def __init__(self, nombre='*', ubicacion='*', puntaje=0, precio=float("inf")):
        
        """ nombre y ubicación deben ser cadenas no vacías,
            puntaje y precio son números.
            Si el precio es 0 se reemplaza por infinito. """
        
        if es_cadena_no_vacia(nombre):
            self.nombre = nombre
        else:
            raise TypeError("El nombre debe ser una cadena no vacía")
        
        if es_cadena_no_vacia(ubicacion):
            self.ubicacion = ubicacion
        else:
            raise TypeError("La ubicacion debe ser una cadena no vacía")
        
        if es_numero(puntaje):
            self.puntaje = puntaje
        else:
            raise TypeError("El puntaje debe ser un número")
        
        if es_numero(precio):
            if precio != 0:
                self.precio = precio
            else:
                raise TypeError("El precio debe ser un número")
                
    def __str__(self):
        """ Muestra el hotel según lo requerido. """
        return (self.nombre + " de " + self.ubicacion + \
               " - Puntaje: " + str(self.puntaje) + " - Precio: "+ \
                str(self.precio)+ " pesos.")
    
def es_cadena_no_vacia(cadena):
    """ Valida si una cadena de texto se encuentra vacía o no. """
    if len(cadena) > 0:
        return cadena

def es_numero(valor):
    """ Indica si un valor es númerico o no. """
    return isinstance(valor, (int, float, complex))    

Con este código tenemos ya la posibilidad de construir hoteles, con los atributos de los tipos
correspondientes, y de mostrar los hoteles según nos lo han solicitado.

In [3]:
h = Hotel("Hotel City", "Mercedes", 3.25, 78)

In [4]:
print(h)

Hotel City de Mercedes - Puntaje: 3.25 - Precio: 78 pesos.


### 14.5.1. Métodos para comparar objetos

Para resolver las comparaciones entre hoteles, será necesario definir algunos métodos especiales
que permiten comparar objetos.

En particular, cuando se quiere que los objetos puedan ser ordenados, el método que se
debe definir es __cmp__, que debe devolver:

Un valor entero menor a cero, si el primer parámetro es menor al segundo.

Un valor entero mayor a cero, si el primer parámetro es mayor que el segundo.

Cero, si ambos parámetros son iguales.

Para crear el método __cmp__, definiremos primero un método auxiliar ratio(self)
que calcula la relación calidad-precio de una instancia de Hotel según la fórmula indicada:

In [7]:
def ratio(self):
    """ Calcula la relación calidad-precio de un hotel de acuerdo 
        a la fórmula que nos dió el cliente. """
    return ((self.puntaje**2)*10.)/self.precio

A partir de este método es muy fácil crear un método __cmp__ que cumpla con la especificación
previa.

In [9]:
def __cmp__(self, otro):
    diferencia = self.ratio() - otro.ratio()
    if diferencia < 0:
        return -1
    elif diferencia > 0:
        return 1
    else:
        return 0

In [2]:
class Hotel():
    """ Hotel: sus atributos son: nombre, ubicación, puntaje y precio. """
    
    def __init__(self, nombre='*', ubicacion='*', puntaje=0, precio=float("inf")):
        
        """ nombre y ubicación deben ser cadenas no vacías,
            puntaje y precio son números.
            Si el precio es 0 se reemplaza por infinito. """
        
        if es_cadena_no_vacia(nombre):
            self.nombre = nombre
        else:
            raise TypeError("El nombre debe ser una cadena no vacía")
        
        if es_cadena_no_vacia(ubicacion):
            self.ubicacion = ubicacion
        else:
            raise TypeError("La ubicacion debe ser una cadena no vacía")
        
        if es_numero(puntaje):
            self.puntaje = puntaje
        else:
            raise TypeError("El puntaje debe ser un número")
        
        if es_numero(precio):
            if precio != 0:
                self.precio = precio
            else:
                raise TypeError("El precio debe ser un número")
                
    def __str__(self):
        """ Muestra el hotel según lo requerido. """
        return (self.nombre + " de " + self.ubicacion + \
               " - Puntaje: " + str(self.puntaje) + " - Precio: "+ \
                str(self.precio)+ " pesos.")
    
    def __cmp__(self, otro):
        diferencia = self.ratio() - otro.ratio()
        if diferencia < 0:
            return -1
        elif diferencia > 0:
            return 1
        else:
            return 0
        
def ratio(self):
    """ Calcula la relación calidad-precio de un hotel de acuerdo 
        a la fórmula que nos dió el cliente. """
    return ((self.puntaje**2)*10.)/self.precio
    
def es_cadena_no_vacia(cadena):
    """ Valida si una cadena de texto se encuentra vacía o no. """
    if len(cadena) > 0:
        return cadena

def es_numero(valor):
    """ Indica si un valor es númerico o no. """
    return isinstance(valor, (int, float, complex))

In [25]:
h = Hotel("Hotel City", "Mercedes", 3.25, 78)

In [26]:
i = Hotel("Hotel Mascardi", "Bariloche", 6, 150)

In [27]:
str(i) < str(h)

False

In [28]:
str(i) == str(h)

False

In [29]:
str(i) > str(h)

True

### 14.5.2. Ordenar de menor a mayor listas de hoteles

En una unidad anterior vimos que se puede ordenar una lista usando el método sort:

In [30]:
l1 = [10,-5, 8, 12, 0]
l1.sort()
l1

[-5, 0, 8, 10, 12]

De la misma forma, una vez que hemos definido el método __cmp__, podemos ordenar listas
de hoteles, ya que internamente el método sort comparará los hoteles mediante el método
de comparación que hemos definido:

In [3]:
h1=Hotel("Hotel 1* normal", "MDQ", 1, 10)
h2=Hotel("Hotel 2* normal", "MDQ", 2, 40)
h3=Hotel("Hotel 3* carisimo", "MDQ", 3, 130)
h4=Hotel("Hotel vale la pena" ,"MDQ", 4, 130)

In [10]:
lista = [ h1, h2, h3, h4 ]
lista.sort(key=lambda x:x.precio)

In [11]:
for x in lista:
    print(x)

Hotel 1* normal de MDQ - Puntaje: 1 - Precio: 10 pesos.
Hotel 2* normal de MDQ - Puntaje: 2 - Precio: 40 pesos.
Hotel 3* carisimo de MDQ - Puntaje: 3 - Precio: 130 pesos.
Hotel vale la pena de MDQ - Puntaje: 4 - Precio: 130 pesos.


### 14.5.3. Otras formas de comparación

Si además de querer listar los hoteles por su relación calidad-precio también se quiere poder
listarlos según su puntaje, o según su precio, no se lo puede hacer mediante el método
__cmp__.

Para situaciones como esta, sort puede recibir, opcionalmente, otro parámetro que es la
función de comparación a utilizar. Esta función deberá cumplir con el mismo formato que el
método __cmp__, pero puede ser una función cualquiera, ya sea un método de una clase o una
función externa.

Además, para simplificar la escritura de este tipo de funciones, podemos utilizar la función
de Python cmp, que si le pasamos dos númeroes, devuelve los valores de la forma que
necesitamos.

In [14]:
def cmpPrecio(self, otro):
    """ Compara dos hoteles por su precio. """
    return cmp(self.precio, otro.precio)

In [15]:
def cmpPuntaje(self, otro):
    """ Compara dos hoteles por su puntaje. """
    return cmp(self.puntaje, otro.puntaje)

In [16]:
class Hotel():
    """ Hotel: sus atributos son: nombre, ubicación, puntaje y precio. """
    
    def __init__(self, nombre='*', ubicacion='*', puntaje=0, precio=float("inf")):
        
        """ nombre y ubicación deben ser cadenas no vacías,
            puntaje y precio son números.
            Si el precio es 0 se reemplaza por infinito. """
        
        if es_cadena_no_vacia(nombre):
            self.nombre = nombre
        else:
            raise TypeError("El nombre debe ser una cadena no vacía")
        
        if es_cadena_no_vacia(ubicacion):
            self.ubicacion = ubicacion
        else:
            raise TypeError("La ubicacion debe ser una cadena no vacía")
        
        if es_numero(puntaje):
            self.puntaje = puntaje
        else:
            raise TypeError("El puntaje debe ser un número")
        
        if es_numero(precio):
            if precio != 0:
                self.precio = precio
            else:
                raise TypeError("El precio debe ser un número")
                
    def __str__(self):
        """ Muestra el hotel según lo requerido. """
        return (self.nombre + " de " + self.ubicacion + \
               " - Puntaje: " + str(self.puntaje) + " - Precio: "+ \
                str(self.precio)+ " pesos.")
    
    def __cmp__(self, otro):
        diferencia = self.ratio() - otro.ratio()
        if diferencia < 0:
            return -1
        elif diferencia > 0:
            return 1
        else:
            return 0
        
    def cmpPrecio(self, otro):
        """ Compara dos hoteles por su precio. """
        return cmp(self.precio, otro.precio)
    
    def cmpPuntaje(self, otro):
        """ Compara dos hoteles por su puntaje. """
        return cmp(self.puntaje, otro.puntaje)
        
def ratio(self):
    """ Calcula la relación calidad-precio de un hotel de acuerdo 
        a la fórmula que nos dió el cliente. """
    return ((self.puntaje**2)*10.)/self.precio
    
def es_cadena_no_vacia(cadena):
    """ Valida si una cadena de texto se encuentra vacía o no. """
    if len(cadena) > 0:
        return cadena

def es_numero(valor):
    """ Indica si un valor es númerico o no. """
    return isinstance(valor, (int, float, complex))

Así, para ordenar según el precio, deberemos hacerlo de la siguiente forma:

In [17]:
h1 = Hotel("Hotel Guadalajara", "Pinamar", 2, 55)
h2 = Hotel("Hostería París", "Rosario", 1, 35)
h3 = Hotel("Apart-Hotel Estocolmo", "Esquel", 3, 105)
h4 = Hotel("Posada El Cairo", "Salta", 2.5, 15)

In [ ]:
lista = [ h1, h2, h3, h4 ]
lista.sort(__cmp__=Hotel.cmpPrecio)

In [ ]:
for hotel in lista:
    print(hotel)

### 14.5.4. Comparación sólo por igualdad o desigualdad

Existen clases, como la clase Punto vista anteriormente, que no se pueden ordenar, ya que
no se puede decir si dos puntos son menores o mayores, con lo cual no se puede implementar
un método __cmp__.

Pero en estas clases, en general, será posible comparar si dos objetos son o no iguales, es
decir si tienen o no el mismo valor, aún si se trata de objetos distintos.

In [3]:
class Punto(object):
    """Representación de un punto en el plano, los atributos x e y 
       que representan los valores de las coordenadas cartesianas."""
    def __init__(self, x=0, y=0):
        """ Constructor de Punto, x e y deben ser numéricos,
            de no ser así, se levanta una excepción TypeError """
        if es_numero(x) and es_numero(y):
            self.x = x
            self.y = y
        else:
            raise TypeError("x e y deben ser valores númericos")
    
    def restar(self, otro):
        """ Devuelve un nuevo punto, con la resta entre dos puntos. """
        return Punto(self.x - otro.x, self.y - otro.y)
    
    def norma(self):
        """ Devuelve la norma del vector que va desde el origen
            hasta el punto. """
        return (self.x*self.x + self.y*self.y)**0.5
    
    def distancia(self, otro):
        """ Devuelve la distancia entre ambos puntos. """
        r = self.restar(otro)
        return r.norma()
    
def es_numero(valor):
    """ Indica si un valor es númerico o no. """
    return isinstance(valor, (int, float, complex))

In [21]:
p = Punto(3,4)
q = Punto(3,4)
p == q

False

En este caso, por más que los puntos tengan el mismo valor, al no estar definido ningún
método de comparación Python no sabe cómo comparar los valores, y lo que compara son las
variables. p y q son variables distintas, por más que tengan los mismos valores.

Para obtener el comportamiento esperado en estos casos, se redefinen los métodos __eq__
(correspondiente al operador ==) y __ne__ (correspondiente a != o <>).

De forma que para poder comparar si dos puntos son o no iguales, deberemos agregar los
siguientes dos métodos a la clase Punto:

In [1]:
def __eq__(self, otro):
    """ Devuelve si dos puntos son iguales. """
    return self.x == otro.x and self.y == otro.y

In [2]:
def __ne__(self, otro):
    """ Devuelve si dos puntos son distintos. """
    return not self == otro

In [4]:
class Punto(object):
    """Representación de un punto en el plano, los atributos x e y 
       que representan los valores de las coordenadas cartesianas."""
    def __init__(self, x=0, y=0):
        """ Constructor de Punto, x e y deben ser numéricos,
            de no ser así, se levanta una excepción TypeError """
        if es_numero(x) and es_numero(y):
            self.x = x
            self.y = y
        else:
            raise TypeError("x e y deben ser valores númericos")
    
    def __eq__(self, otro):
        """ Devuelve si dos puntos son iguales. """
        return self.x == otro.x and self.y == otro.y
    
    def __ne__(self, otro):
        """ Devuelve si dos puntos son distintos. """
        return not self == otro
    
    def restar(self, otro):
        """ Devuelve un nuevo punto, con la resta entre dos puntos. """
        return Punto(self.x - otro.x, self.y - otro.y)
    
    def norma(self):
        """ Devuelve la norma del vector que va desde el origen
            hasta el punto. """
        return (self.x*self.x + self.y*self.y)**0.5
    
    def distancia(self, otro):
        """ Devuelve la distancia entre ambos puntos. """
        r = self.restar(otro)
        return r.norma()
    
def es_numero(valor):
    """ Indica si un valor es númerico o no. """
    return isinstance(valor, (int, float, complex))

In [9]:
p = Punto(3,4)
q = Punto(3,4)

In [6]:
p == q

True

In [7]:
p != q

False

In [12]:
r = Punto(2,3)

In [13]:
p == r

False

In [14]:
p != r

True

### 15. Polimorfismo, Herencia y Delegación

En esta unidad veremos algunos temas que son centrales a la programación orientada a
objetos: polimorfismo, herencia y delegación.

### 15.1. Polimorfismo

El concepto de polimorfismo (del griego muchas formas) implica que si en una porción de
código se invoca un determinado método de un objeto, podrán obtenerse distintos resultados
según la clase del objeto. Esto se debe a que distintos objetos pueden tener un método con un
mismo nombre, pero que realice distintas operaciones.

En las unidades anteriores, varias veces utilizamos las posibilidades provistas por el polimorfismo,
sin haberle puesto este nombre.

Se vio, por ejemplo, que es posible recorrer cualquier tipo de secuencia (ya sea una lista,
una tupla, un diccionario, un archivo o cualquier otro tipo de secuencia) utilizando la misma
estructura de código (for elemento in secuencia).

De la misma forma, hemos utilizado funciones que podían trabajar con los distintos tipos
numéricos sin hacer distinción sobre de qué tipo de número se trataba (entero, real, largo o
complejo).

Por otro lado, en la unidad anterior se vio también que al construir una clase, es posible
incluir el método __str__ para que cuando se quiera imprimir el objeto se lo haga de la forma
deseada; así como una gran variedad de otros métodos especiales, que permiten que operadores
comunes sean utilizados sobre distintos tipos de objetos

### 15.1.1. Interfaz

Llamamos interfaz a un conjunto de funciones, métodos o atributos con nombres específicos.
Una interfaz es un contrato entre el programador que realiza una clase y el que la utiliza,
puede consistir en uno solo o varios métodos o atributos.

Por ejemplo, para que un objeto se pueda comparar con otros, debe cumplir con la interfaz
comparable, que en Python implica incluir el método __cmp__ visto en la unidad anterior.

La idea de polimorfismo se basa, entonces, en utilizar distintos tipos de datos a través de
una interfaz común.

### 15.1.2. Redefinición de métodos

Llamamos redefinición a la acción de definir un método con el mismo nombre en distintas
clases, de forma tal que provea una interfaz.

Un bloque de código será polimórfico cuando dentro de ese código se realicen llamadas a
métodos que puedan estar redefinidos en distintas clases.

Tomemos por ejemplo el caso ya mencionado en el que se recorre una secuencia (lista, tupla,
archivo, etc) mediante una misma estructura de código. Esto es posible gracias a la redefinición
del método especial __iter__, que devuelve un iterador. Un bloque que utiliza una secuencia
en forma genérica es, entonces, un bloque polimórfico.

En la vida real, cuando analizamos las funciones de respiración, reproducción o alimentación,
de los seres vivos vemos que siempre se repite el mismo patrón: si bien la acción en todos
los casos es la misma, puede suceder que haya diferencias en la implementación en cada tipo,
ya que no es lo mismo la respiración de una mojarrita que la de un malvón, no es lo mismo la
reproducción de una ameba que la de un elefante.

De la misma forma, al implementar nuestras clases, debemos proveer distintas implementaciones
de los métodos que se llaman igual, para que puedan comportarse polimórficamente,
como ser las redefiniciones de los métodos __str__ o __cmp__ vistas en la unidad anterior.

En particular en Python, la sobrecarga de operadores, mencionada anteriormente, es un proceso
que se realiza mediante la redefinición de algunos métodos especiales. En otros lenguajes se
utilizan técnicas distintas para obtener el mismo resultado.

### 15.1.3. Un ejemplo de polimorfismo

En la unidad anterior se vio la clase Punto que representa a un punto en el plano. Es posible
definir también una clase Punto3D, que represente un punto en el espacio. Esta nueva clase
contendrá los mismos métodos que se vieron para Punto, pero para tres coordenadas.

Si a ambas clases le agregamos un método para multiplicar por un escalar (__mul__(self, escalar)),
podríamos tener la siguiente función polimórfica:

In [15]:
def obtener_versor(punto):
    norma = punto.norma()
    return punto * (1.0 / norma)

Esta función devolverá un versor de dos dimensiones o de tres dimensiones, según a qué
clase pertenezca la variable punto.

Otro ejemplo que ya hemos visto, utilizando secuencias, es usar un diccionario para contar
la frecuencia de aparación de elementos dentro de una secuencia cualquiera.

In [25]:
def frecuencias(secuencia):
    """ Calcula las frecuencias de aparición de los elementos de
        la secuencia recibida.
        Devuelve un diccionario con elementos: { valor: frecuencia }
    """
    # crea un diccionario vacío
    frec = dict()
    # recorre la secuencia
    for elemento in secuencia:
        frec[elemento] = frec.get(elemento, 0)+1
    return frec

Vemos que el parámetro secuencia puede ser de cualquier tipo que se encuentre dentro
de la “familia” de las secuencias. En cambio, si llamamos a la función con un entero se levanta
una excepción.

In [18]:
frecuencias(["peras", "manzanas", "peras", "manzanas", "uvas"])

{'peras': 2, 'manzanas': 2, 'uvas': 1}

In [19]:
frecuencias((1,3,4,2,3,1))

{1: 2, 3: 2, 4: 1, 2: 1}

In [20]:
frecuencias("Una frase")

{'U': 1, 'n': 1, 'a': 2, ' ': 1, 'f': 1, 'r': 1, 's': 1, 'e': 1}

In [22]:
ran = range(3,10,2)

In [23]:
frecuencias(ran)

{3: 1, 5: 1, 7: 1, 9: 1}

In [24]:
frecuencias(4)

TypeError: 'int' object is not iterable

### 15.2. Herencia

La herencia es un mecanismo de la programación orientada a objetos que sirve para crear
clases nuevas a partir de clases preexistentes. Se toman (heredan) atributos y comportamientos
de las clases viejas y se los modifica para modelar una nueva situación.

La clase vieja se llama clase base y la que se construye a partir de ella es una clase derivada.

Por ejemplo, a partir de una clase Persona (que contenga como atributos identificacion,
nombre, apellido) podemos construir la clase AlumnoFIUBA que extiende a Persona y
agrega como atributo el padron.

Para indicar el nombre de la clase base, se la pone entre paréntesis a continuación del nombre
de la clase (en lugar de la expresión object que poníamos anteriormente –en realidad
object es el nombre de la clase base genérica–).

Definimos Persona:

In [26]:
class Persona(object):
    """ Clase que representa una persona. """
    def __init__(self, identificacion, nombre, apellido):
        # Constructor de persona
        self.identificacion = identificacion
        self.nombre = nombre
        self.apellido = apellido
    
    def __str__(self):
        return " %s: %s, %s" % \
            (str(self.identificacion), self.apellido, self.nombre)

A continuación definimos AlumnoFIUBA como derivada de Persona, de forma tal que
inicialice el nuevo atributo, pero a su vez utilice la inicialización de Persona para las atributos
de la clase base:

In [41]:
class AlumnoFIUBA(Persona):
    """ Clase que representa a un alumno FIUBA. """
    def __init__(self, identificacion, nombre, apellido, padron):
        # Constructor de AlumnoFIUBA
        # llamamos al constructor de Persona 
        Persona.__init__(self, identificacion, nombre, apellido)
        # agregamos el nuevo atributo
        self.padron = padron

Probamos la nueva clase

In [42]:
a = AlumnoFIUBA("DNI 35123456", "Damien", "Thorn", "98765")
print(a)

 DNI 35123456: Thorn, Damien


Vemos que se heredó el método __str__ de la clase base. Si queremos, podemos redefinirlo:

In [43]:
def __str__(self):
    """ Devuelve una cadena representativa del alumno """
    return " %s: %s, %s" % \
        (str(self.padron), self.apellido, self.nombre)

In [45]:
class AlumnoFIUBA(Persona):
    """ Clase que representa a un alumno FIUBA. """
    def __init__(self, identificacion, nombre, apellido, padron):
        # Constructor de AlumnoFIUBA
        # llamamos al constructor de Persona 
        Persona.__init__(self, identificacion, nombre, apellido)
        # agregamos el nuevo atributo
        self.padron = padron
    
    def __str__(self):
        #Devuelve una cadena representativa del alumno
        return " %s: %s, %s" % \
            (self.padron, self.apellido, self.nombre)

Volvemos a probar:

In [46]:
a = AlumnoFIUBA("35123456", "Damien", "Thorn", "98765")
print(a)

 98765: Thorn, Damien


De una clase base se pueden construir muchas clases derivadas, así como hemos derivado
alumnos, podríamos derivar docentes, empleados, clientes, proveedores, o lo que fuera necesario
según la aplicación que estemos desarrollando.

En el caso de Python, también se puede construir una clase derivada a partir de varias clases
base (por ejemplo, un ayudante de segunda en la UBA es un alumno que también trabaja de
docente). Esta posbilidad se llama Herencia Múltiple, pero no la detallaremos por ahora.

### La clase de las figuras

Un ejemplo clásico de herencia es el de las figuras cerradas en el plano, con un método para
calcular el área. En este caso, la clase base no tiene comportamiento definido ni atributos, dado
que cada figura tiene atributos muy distintos (radio en el caso del círculo, base y altura en el
caso del triángulo, etc.), y en cuanto al cálculo del área, cada figura tiene una fórmula diferente:

La clase base:

In [47]:
class Figura(object):
    """ Una figura en el plano. """
    def area(self):
        # este método debe ser redifinido. 
        pass

Los círculos:

In [49]:
from math import pi

class Circulo(Figura):
    """ Un círculo en el plano. """
    def __init__(self, radio=0):
        # constructor de círculo.
        self.radio = radio
    
    def area(self):
        # devuelve el área del círculo.
        return pi * self.radio * self.radio

Y los triángulos:

In [50]:
class Triangulo(Figura):
    """ Un triángulo en el plano. """
    def __init__(self, base=0, altura=0):
        # constructor de triángulo,
        self.base = base
        self.altura = altura
    
    def area(self):
        """ Devuelve el área del triángulo. """
        return self.base * self.altura / 2

Y ahora las pruebas:

In [51]:
c = Circulo(4)
c.area()

50.26548245743669

In [52]:
t = Triangulo(3,5)
t.area()

7.5

### 15.3. Delegación

Llamamos delegación a la situación en la que una clase contiene (como atributos) una o
más instancias de otra clase, a las que delegará parte de sus funcionalidades. Esta relación entre
clases suele ser la más indicada cuando es necesaria una asociación entre las clases pero el principio
de Liskov no se cumple. También puede verse como la relación entre clases “S contiene a
T”. Por ejemplo, Vehículo contiene un Motor, pero Alumno no contiene a Persona, sino que es
una Persona.

Por ejemplo, la clase Hotel vista en la unidad anterior, podría contener una clase
Disponibilidad, que almacene la disponibilidad de las habitaciones del hotel para distintas
fechas. La clase Hotel debería tener, entonces, los métodos consultar_disponibilidad,
reservar y cancelar, que todos delegarían en la clase Disponibilidad su funcionamiento
principal.

### Delegación y Referencias

Queremos construir una clase Rectangulo, que se describe mediante los siguientes atributos:

Longitud de su base: un número.

Longitud de su altura: un número.

El punto del plano de su esquina inferior izquierda: un punto del plano.

In [7]:
class Punto(object):
    """Representación de un punto en el plano, los atributos x e y 
       que representan los valores de las coordenadas cartesianas."""
    def __init__(self, x=0, y=0):
        """ Constructor de Punto, x e y deben ser numéricos,
            de no ser así, se levanta una excepción TypeError """
        if es_numero(x) and es_numero(y):
            self.x = x
            self.y = y
        else:
            raise TypeError("x e y deben ser valores númericos")
            
    def __str__(self):
        """ Muestra el punto como un par ordenado. """
        return "(" + str(self.x) + ", " + str(self.y) + ")"
    
    def __add__(self, otro):
        """ Devuelve la suma de ambos puntos. """
        return Punto(self.x + otro.x, self.y + otro.y)
    
    def __sub__(self,otro):
        """ Devuelve la resta de ambos puntos. """
        return Punto(self.x - otro.x, self.y - otro.y)
    
    def restar(self, otro):
        """ Devuelve un nuevo punto, con la resta entre dos puntos. """
        return Punto(self.x - otro.x, self.y - otro.y)
    
    def norma(self):
        """ Devuelve la norma del vector que va desde el origen
            hasta el punto. """
        return (self.x*self.x + self.y*self.y)**0.5
    
    def distancia(self, otro):
        """ Devuelve la distancia entre ambos puntos. """
        r = self.restar(otro)
        return r.norma()
    
def es_numero(valor):
    """ Indica si un valor es númerico o no. """
    return isinstance(valor, (int, float, complex))

__Código 15.1__ Rectangulo.py: Clase para modelar un Rectángulo

In [8]:
class Rectangulo(object):
    """ Esta clase modela un rectángulo en el plano. """
    
    def __init__(self, base, altura, origen):
        """ base (número) es la longitud de su base,
            altura (número) es la longitud de su base,
            origen (Punto) es el punto del plano de su esquina
                            inferior izquierda. """
        self.base = base
        self.altura = altura
        self.origen = origen
        
    def trasladar(self, dx = 0, dy = 0):
        self.origen = self.origen + Punto(dx,dy)
        
    def area(self):
        return self.base * self.altura
    
    def __str__(self):
        """ muestra el rectangulo """
        return "Base: %s, Altura: %s, Esquina inf. izq.: %s " % \
                (self.base, self.altura, self.origen)

Incluiremos métodos para inicializar y mostrar, para calcular el área y para trasladar el
rectángulo en el plano.

La implementación básica puede verse en el Código 15.1. Se puede ver que el rectángulo
realiza internamente la operación para calcular el área, pero para la operación del traslado,
delega la suma de los puntos al operador __add__ de la clase Punto.

Recordamos que cuando se hace self.origen + Punto(dx,dy), Python llama al método
__add__ de la clase Punto, que recibe los dos puntos y devuelve un nuevo punto con la
suma de ambos.

Para construir y utilizar el rectángulo, lo haremos de la siguiente forma:

In [9]:
r = Rectangulo(2, 3, Punto(1, 2))

In [10]:
print(r)

Base: 2, Altura: 3, Esquina inf. izq.: (1, 2) 


In [13]:
print(r.area())

6


El punto que describe la posición de la esquina inferior izquierda del rectángulo es un objeto
Punto. El atributo origen contiene una referencia a dicho objeto.

Utilizando el método trasladar, podemos modificar el valor del punto contenido dentro
del rectángulo.

In [14]:
r.trasladar(2,4)

In [15]:
print(r)

Base: 2, Altura: 3, Esquina inf. izq.: (3, 6) 


También es posible directamente reemplazar el punto contenido, por un nuevo punto.

In [16]:
q = Punto(7,2)

In [17]:
r.origen = q

In [18]:
print(r)

Base: 2, Altura: 3, Esquina inf. izq.: (7, 2) 


### 16. Listas enlazadas

En esta unidad, nos dedicaremos a construir nuestras propias listas, que consistirán de cadenas
de objetos enlazadas mediante referencias, como las vistas en la unidad anterior.

Si bien Python ya cuenta con sus propias listas, las listas enlazadas que implementaremos
en esta unidad nos resultarán también útiles.

### 16.1. Una clase sencilla de vagones

En primer lugar, definiremos una clase muy simple, Nodo, que se comportará como un
vagón: tendrá sólo dos atributos: dato, que servirá para almacenar cualquier información, y
prox, que servirá para poner una referencia al siguiente vagón.

Además, como siempre, implementaremos el constructor y el método __str__ para poder
imprimir el contenido del nodo.

In [21]:
class Nodo(object):
    def __init__(self, dato=None, prox=None):
        self.dato = dato
        self.prox = prox
    
    def __str__(self):
        return str(self.dato)

Ejecutamos este código

In [22]:
v3=Nodo("Bananas")

In [23]:
v2=Nodo("Peras", v3)

In [24]:
v1=Nodo("Manzanas", v2)

In [25]:
print(v1)

Manzanas


In [26]:
print(v2)

Peras


In [27]:
print(v3)

Bananas


El atributo prox de v3 tiene una referencia nula, lo que indica que v3 es el último vagón
de nuestra estructura.

Hemos creado una lista en forma manual. Si nos interesa recorrerla, podemos hacer lo siguiente:

In [29]:
def verLista(nodo):
    """ Recorre todos los nodos a través de sus enlaces,
        mostrando sus contenidos. """
    
    # ciclo mientras nodo no es None
    while nodo:
        # muestra el dato
        print(nodo)
        # ahora nodo apunta a nodo.prox
        nodo = nodo.prox
        
verLista(v1)

Manzanas
Peras
Bananas


Es interesante notar que la estructura del recorrido de la lista es el siguiente:

Se le pasa a la función sólo la referencia al primer nodo.

El resto del recorrido se consigue siguiendo las cadena de referencias dentro de los nodos.

Si se desea desenganchar un vagón del medio de la lista, alcanza con cambiar el enganche:

In [31]:
v1.prox=v3
verLista(v1)

Manzanas
Bananas


In [32]:
v1.prox=None
verLista(v1)

Manzanas


De esta manera también se pueden generar estructuras impensables.

¿Qué sucede si escribimos v1.prox = v1? La representación es finita y sin embargo en
este caso verLista(v1) no termina más. Hemos creado una lista infinita, también llamada
lista circular.

### 16.1.1. Caminos

En una lista cualquiera, como las vistas antes, si seguimos las flechas dadas por las referencias,
obtenemos un camino en la lista.

Los caminos cerrados se denominan ciclos. Son ciclos, por ejemplo, la autorreferencia de v1
a v1, como así también una flecha de v1 a v2 seguida de una flecha de v2 a v1.

### 16.1.2. Referenciando el principio de la lista

Una cuestión no contemplada hasta el momento es la de mantener una referencia a la lista
completa. Por ahora para nosotros la lista es la colección de nodos que se enlazan a partir de
v1. Sin embargo puede suceder que querramos borrar a v1 y continuar con el resto de la lista
como la colección de nodos a tratar (en las listas de Python, del lista[0] no nos hace perder
la referencia a lista).

Para ello lo que haremos es asociar una referencia al principio de la lista, que llamaremos
lista, y que mantendremos independientemente de cuál sea el nodo que está al principio de
la lista:

In [33]:
v3=Nodo("Bananas")

In [34]:
v2=Nodo("Peras", v3)

In [35]:
v1=Nodo("Manzanas", v2)

In [39]:
lista=v1

In [40]:
verLista(lista)

Manzanas
Peras
Bananas


Ahora sí estamos en condiciones de borrar el primer elemento de la lista sin perder la identidad
de la misma:

In [41]:
lista=lista.prox

In [42]:
verLista(lista)

Peras
Bananas


### 16.2. Tipos abstractos de datos

Los tipos nuevos que habíamos definido en unidades anteriores fueron tipos de datos concretos:
un punto se definía como un par ordenado de números, un hotel se definía por dos
cadenas de caracteres (nombre y unicación) y dos números (calidad y precio), etc.

Vamos a ver ahora una nueva manera de definir datos: por las operaciones que tienen y por
lo que tienen que hacer esas operaciones (cuál es el resultado esperado de esas operaciones).

Esa manera de definir datos se conoce como tipos abstractos de datos o TADs.

Lo novedoso de este enfoque respecto del anterior es que en general se puede encontrar
más de una representación mediante tipos concretos para representar el mismo TAD, y que se
puede elegir la representación más conveniente en cada caso, según el contexto de uso.

Los programas que los usan hacen referencia a las operaciones que tienen, no a la representación,
y por lo tanto ese programa sigue funcionando si se cambia la representación.

Dentro del ciclo de vida de un TAD hay dos fases: la programación del TAD y la construcción
de los programas que lo usan.

Durante la fase de programación del TAD, habrá que elegir una representación, y luego
programar cada uno de los métodos sobre esa representación.

Durante la fase de construcción de los programas, no será relevante para el programador
que utiliza el TAD cómo está implementado, sino únicamente los métodos que posee.

### 16.3. La clase ListaEnzalada

Basándonos en los nodos implementados anteriormente, pero buscando deslindar al programador
que desea usar la lista de la responsabilidad de manipular las referencias, definiremos
ahora la clase ListaEnlazada, de modo tal que no haya que operar mediante las referencias
internas de los nodos, sino que se lo pueda hacer a través de operaciones de lista.

Más allá de la implementación en particular, se podrá notar que implementaremos los mismos
métodos de las listas de Python, de modo que más allá del funcionamiento interno, ambas
serán listas.

Definimos a continuación las operaciones que inicialmente deberá cumplir la clase
ListaEnlazada.

___str___, para mostrar la lista.

__len__, para calcular la longitud de la lista.

append(x), para agregar un elemento al final de la lista.

insert(i, x), para agregar el elemento x en la posición i (levanta una excepción si la
posición i es inválida).

remove(x), para eliminar la primera aparición de x en la lista (levanta una excepción si
x no está).

pop([i]), para borrar el elemento que está en la posición i y devolver su valor. Si no
se especifica el valor de i, pop() elimina y devuelve el elemento que está en el último
lugar de la lista (levanta una excepción si se hace referencia a una posición no válida de
la lista).

index(x), devuelve la posición de la primera aparición de x en la lista (levanta una
excepción si x no está).

Más adelante podrán agregarse a la lista otros métodos que también están implementados
por las listas de Python.

Valen ahora algunas consideraciones más antes de empezar a implementar la clase:

Por lo dicho anteriormente, es claro que la lista deberá tener como atributo la referencia
al primer nodo que la compone.

Como vamos a incluir un método __len__, consideramos que no tiene sentido recorrer
la lista cada vez que se lo llame, para contar cuántos elementos tiene, alcanza con agregar
un atributo más (la longitud de la lista), que se inicializa en 0 cuando se crea la lista vacía,
se incrementa en 1 cada vez que se agrega un elemento y se decrementa en 1 cada vez
que se borra un elemento.

Por otro lado, como vamos a incluir todas las operaciones de listas que sean necesarias
para operar con ellas, no es necesario que la clase Nodo esté disponible para que otros
programadores puedan modificar (y romper) las listas a voluntad usando operaciones de
nodos. Para eso incluiremos la clase Nodo de manera privada (es decir oculta), de modo
que la podamos usar nosotros como dueños (fabricantes) de la clase, pero no cualquier
programador que utilice la lista.

Python tiene una convención para hacer que atributos, métodos o clases dentro de una clase
dada no puedan ser usados por los usuarios, y sólo tengan acceso a ellos quienes programan la
clase: su nombre tiene que empezar con un guión bajo y terminar sin guión bajo. Así que para
hacer que los nodos sean privados, nombraremos a esa clase como _Nodo, y la dejaremos tal
como hasta ahora.

In [43]:
class _Nodo(object):
    def __init__(self, dato=None, prox=None):
        self.dato = dato
        self.prox = prox
    
    def __str__(self):
        return str(self.dato)

### 16.3.1. Construcción de la lista

Empezamos escribiendo la clase con su constructor.

In [44]:
class ListaEnlazada(object):
    """ Modela una lista enlazada, compuesta de Nodos. """

    def __init__(self):
        """ Crea una lista enlazada vacía. """
        #prim: apuntará al primer nodo - None con la lista vacía
        self.prim = None
        #len: longitud de la lista - 0 con la lista vacía
        self.len = 0

__Ejercicio 16.1.__ Escribir los métodos __str__ y __len__ para la lista.

In [77]:
class ListaEnlazada(object):
    """ Modela una lista enlazada, compuesta de Nodos. """

    def __init__(self):
        """ Crea una lista enlazada vacía. """
        #prim: apuntará al primer nodo - None con la lista vacía
        self.prim = None
        #lon: longitud de la lista - 0 con la lista vacía
        self.len = 0
        
    def __len__(self, lon):
        return len(self.lon)
    
    def __str__(self):
        """ muestra una lista """
        return(self.valor)

### 16.3.2. Eliminar un elemento de una posición

Analizaremos a continuación pop([i]), que borra el elemento que está en la posición i y
devuelve su valor. Si no se especifica el valor de i, pop() elimina y devuelve el elemento que
está en el último lugar de la lista. Por otro lado, levanta una excepción si se hace referencia a
una posición no válida de la lista.

Dado que se trata de una función con cierta complejidad, separaremos el código en las
diversas consideraciones a tener en cuenta.

Si la posición es inválida (i menor que 0 o mayor o igual a la longitud de la lista), se
considera error y se levanta la excepción ValueError.

Esto se resuelve con este fragmento de código:

In [ ]:
#Verificación de los límites
if (i < 0) or (i >= self.len):
    raise IndexError("Índice fuera de rango")

Si no se indica posición, i toma la última posición de la lista.

Esto se resuelve con este fragmento de código:

In [ ]:
# Si no se recibió i, se devuelve el último.
if i == None:
    i = self.len - 1

Cuando la posición es 0 se trata de un caso particular, ya que en ese caso, además de
borrar el nodo, hay que cambiar la referencia de self.prim para que apunte al nodo
siguiente. Es decir, pasar de self.prim -> nodo0 -> nodo1 a self.prim -> nodo1).

Esto se resuelve con este fragmento de código:

In [ ]:
# Caso particular, si es el primero,
# hay que saltear la cabecera de la lista
if i == 0:
    dato = self.prim.dato
    self.prim = self.prim.prox

Vemos ahora el caso general:

Mediante un ciclo, se deben ubicar los nodos npi - 1 y npi que están en las posiciones i-1
e i de la lista, respectivamente, de modo de poder ubicar no sólo el nodo que se borrará, sino también estar en condiciones de saltear el nodo borrado en los enlaces de la lista. La
lista debe pasar de contener el camino npi - 1->npi->npi.prox a contener el camino npi-1
->npi.prox.

In [78]:
lista = ListaEnlazada()

In [79]:
lista.append(1)

AttributeError: 'ListaEnlazada' object has no attribute 'append'

In [ ]:
    def __str__(self):
        """ muestra el rectangulo """
        return "Base: %s, Altura: %s, Esquina inf. izq.: %s " % \
                (self.base, self.altura, self.origen)

In [ ]:
lista = 

In [74]:
lista = ListaEnlazada(0,3)
print(lista.__len__('ASD'))

TypeError: __len__() takes 1 positional argument but 2 were given

In [48]:
lista = ListaEnlazada(0,5)
print(lista)

TypeError: __init__() takes 1 positional argument but 3 were given

voy en la página 165

In [71]:
from Punto import Punto

class Rectangulo(object):
    """ Esta clase modela un rectángulo en el plano. """
    
    def __init__(self, base, altura, origen):
        """ base (número) es la longitud de su base,
            altura (número) es la longitud de su base,
            origen (Punto) es el punto del plano de su esquina
                            inferior izquierda. """
        self.base = base
        self.altura = altura
        self.origen = origen
        
    def trasladar(self, dx = 0, dy = 0):
        self.origen = self.origen + Punto(dx,dy)
        
    def area(self):
        return self.base * self.altura
    
    def __str__(self):
        """ muestra el rectángulo. """
        return "Base: %s, Altura: %s, Esquina inf. izq.: %s " % \
             (self.base, self.altura, self.origen)

ModuleNotFoundError: No module named 'Punto'

 voy en la pagina 154